'use client';
import { useState } from 'react';
import useSWR from 'swr';
import { api, fetcher, paise, fmtDate, ymd, API, getToken } from '@/lib/api';
import { StatusBadge, useToast } from '@/components/ui';
const NEXT: Record<string, string[]> = { PENDING_PAYMENT: ['CONFIRMED', 'CANCELLED'], CONFIRMED: ['PACKED', 'CANCELLED'], PACKED: ['OUT_FOR_DELIVERY', 'CANCELLED'], OUT_FOR_DELIVERY: ['DELIVERED', 'FAILED'], FAILED: ['CONFIRMED'] };
export default function Orders() {
  const [date, setDate] = useState(''); const [status, setStatus] = useState(''); const { show, Toast } = useToast();
  const { data, mutate } = useSWR(`/admin/orders?${date ? 'date=' + date + '&' : ''}${status ? 'status=' + status : ''}`, fetcher);
  const move = async (id: string, s: string) => { try { await api(`/admin/orders/${id}/status`, { method: 'PATCH', body: { status: s } }); mutate(); } catch (e: any) { show(e.message, true); } };
  return <div><Toast /><div className="flex justify-between items-center mb-4"><h1 className="text-2xl font-bold">Orders</h1><div className="flex gap-2"><input type="date" className="input" value={date} onChange={(e) => setDate(e.target.value)} /><select className="input" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{['PENDING_PAYMENT', 'CONFIRMED', 'PACKED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'FAILED'].map((s) => <option key={s}>{s}</option>)}</select><button className="btn-secondary" onClick={() => setDate(ymd(new Date(Date.now() + 86400000)))}>Tomorrow</button></div></div>
    <div className="card overflow-auto"><table className="tbl"><thead><tr><th>#</th><th>Delivery</th><th>Customer</th><th>Zone / address</th><th>Items</th><th>kg</th><th>Total</th><th>Pay</th><th>Status</th><th>Route</th><th></th></tr></thead><tbody>
      {data?.map((o: any) => <tr key={o.id}><td><a className="underline font-semibold" href={`/admin/orders/${o.id}`}>{o.orderNo}</a>{o.revision > 1 && <small className="text-gray-400"> r{o.revision}</small>}<br /><span className="badge bg-gray-100">{o.channel}</span></td><td>{fmtDate(o.deliveryDate)}<br /><small>{o.slot?.label}</small></td><td>{o.user.name}<br /><small>{o.user.phone}</small></td><td><b>{o.address.zone?.name || '—'}</b><br /><small>{o.address.line1}{o.address.complex ? ', ' + o.address.complex : ''}</small></td><td className="text-xs">{o.items.map((i: any) => `${i.qty}× ${i.sku.code}`).join(', ')}</td><td>{o.totalKg}</td><td>{paise(o.totalPaise)}</td><td className="text-xs">{o.payment?.method}<br /><StatusBadge s={o.payment?.status || '-'} /></td><td><StatusBadge s={o.status} /></td><td className="text-xs">{o.stop ? `stop ${o.stop.seq}` : '—'}</td>
        <td className="text-xs whitespace-nowrap">{(NEXT[o.status] || []).map((s) => <button key={s} className="btn-secondary !py-0.5 !px-2 mr-1 mb-1" onClick={() => move(o.id, s)}>{s.replace(/_/g, ' ')}</button>)}<a className="underline" target="_blank" href={`${API}/v1/orders/${o.id}/invoice.html?t=${getToken()}`}>inv</a></td></tr>)}</tbody></table>{data && !data.length && <div className="text-gray-400 text-center py-6">No orders</div>}</div></div>;
}
