'use client';
import { useState } from 'react';
import useSWR from 'swr';
import { api, fetcher, paise, fmtDate, ymd, API, getToken } from '@/lib/api';
import { Modal, Field, useToast } from '@/components/ui';
export default function Inventory() {
  const [wh, setWh] = useState(''); const { show, Toast } = useToast();
  const { data: summary, mutate: m1 } = useSWR('/inventory/summary' + (wh ? '?warehouseId=' + wh : ''), fetcher); const { data: lots, mutate: m2 } = useSWR('/inventory/lots' + (wh ? '?warehouseId=' + wh : ''), fetcher);
  const { data: whs } = useSWR('/admin/warehouses', fetcher); const { data: vendors } = useSWR('/admin/vendors', fetcher); const { data: cat } = useSWR('/catalog', fetcher); const { data: pos } = useSWR('/admin/purchase-orders', fetcher); const { data: scans } = useSWR('/admin/trace-scans', fetcher, { refreshInterval: 60000 });
  const [grn, setGrn] = useState(false); const [xfer, setXfer] = useState<any>(null); const [adj, setAdj] = useState<any>(null);
  const [f, setF] = useState<any>({ lotNo: 'LOT-' + ymd(new Date()).replace(/-/g, '').slice(2) + '-', vendorId: '', warehouseId: '', varietyId: '', harvestSeason: 'Kharif 2025', milledOn: ymd(new Date()), moisturePct: 12.5, brokenPct: 2.5, costRupees: 44, receivedKg: 1000, poId: '' });
  const refresh = () => { m1(); m2(); };
  const submitGrn = async () => { try { await api('/inventory/grn', { body: { ...f, costPaisePerKg: Math.round(f.costRupees * 100), poId: f.poId || undefined } }); setGrn(false); refresh(); show('Lot received; vendor bill posted'); } catch (e: any) { show(e.message, true); } };
  const [xkg, setXkg] = useState(0); const [xto, setXto] = useState('');
  const submitXfer = async () => { try { await api('/inventory/transfer', { body: { lotId: xfer.id, toWarehouseId: xto, kg: xkg } }); setXfer(null); refresh(); show('Transferred'); } catch (e: any) { show(e.message, true); } };
  const [akg, setAkg] = useState(0); const [areason, setAreason] = useState('DAMAGE'); const [anote, setAnote] = useState('');
  const submitAdj = async () => { try { await api(`/inventory/lots/${adj.id}/adjust`, { body: { kgDelta: areason === 'DAMAGE' ? -Math.abs(akg) : akg, reason: areason, note: anote } }); setAdj(null); refresh(); show('Adjusted'); } catch (e: any) { show(e.message, true); } };
  return <div><Toast /><div className="flex justify-between items-center mb-4"><h1 className="text-2xl font-bold">Stock & lots</h1><div className="flex gap-2"><select className="input" value={wh} onChange={(e) => setWh(e.target.value)}><option value="">All warehouses</option>{whs?.map((w: any) => <option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select><button className="btn-primary" onClick={() => setGrn(true)}>+ Receive stock (GRN)</button></div></div>
    <div className="grid grid-cols-2 xl:grid-cols-4 gap-3 mb-6">{summary?.map((v: any) => <div key={v.id} className={'card ' + (v.low ? 'border-amber-400 bg-amber-50' : '')}><div className="text-xs text-gray-500">{v.code}{v.isAddon && ' · add-on'}</div><div className="font-semibold">{v.name}</div><div className="text-2xl font-bold">{Math.round(v.onHandKg)} <span className="text-sm font-normal">kg</span></div><div className="text-xs text-gray-500">{Object.entries(v.byWarehouse).map(([k, kg]: any) => `${k}: ${Math.round(kg)}`).join(' · ') || 'no stock'}{v.oldestMilledOn && ` · FIFO from ${fmtDate(v.oldestMilledOn)}`}</div>{v.low && <div className="text-xs text-amber-700 font-medium mt-1">Low stock — reorder</div>}</div>)}</div>
    {scans?.length > 0 && <div className={'card mb-6 ' + (scans.some((s: any) => s.flagged) ? 'border-red-400 bg-red-50' : '')}>
      <div className="flex justify-between items-baseline"><div className="font-semibold">Bag QR scans · last 24h</div><div className="text-xs text-gray-500">Customers scanning /trace. One lot from many different IPs = a copied QR — check the bags in the field.</div></div>
      <div className="flex flex-wrap gap-2 mt-2 text-xs">{scans.map((s: any) => <div key={s.lotNo} className={'rounded px-2 py-1 border ' + (s.flagged ? 'bg-red-100 border-red-400 text-red-800 font-semibold' : !s.known ? 'bg-amber-50 border-amber-300' : 'bg-white')}>{s.lotNo}{!s.known && ' (unknown lot!)'} · {s.scans} scan{s.scans === 1 ? '' : 's'} · {s.distinctIps} IP{s.distinctIps === 1 ? '' : 's'}{s.flagged && ' · FLAGGED'}</div>)}</div>
    </div>}
    <div className="card overflow-auto"><table className="tbl"><thead><tr><th>Lot</th><th>Variety</th><th>Warehouse</th><th>Vendor</th><th>Harvest</th><th>Milled</th><th>Aged</th><th>Moist %</th><th>Brokens %</th><th>Cost/kg</th><th>Received</th><th>On hand</th><th></th></tr></thead><tbody>
      {lots?.map((l: any) => <tr key={l.id} className={l.onHandKg <= 0 ? 'opacity-40' : ''}><td className="font-mono text-xs">{l.lotNo}</td><td>{l.variety.name}</td><td><span className="badge bg-gray-100">{l.warehouse.code}</span></td><td className="text-xs">{l.vendor.name}</td><td className="text-xs">{l.harvestSeason}</td><td>{fmtDate(l.milledOn)}</td><td>{Math.floor((Date.now() - new Date(l.milledOn).getTime()) / 2592000000)} mo</td><td className={l.moisturePct > 13 ? 'text-red-600' : ''}>{l.moisturePct}</td><td>{l.brokenPct}</td><td>{paise(l.costPaisePerKg)}</td><td>{l.receivedKg}</td><td><b>{l.onHandKg}</b></td>
        <td className="text-xs whitespace-nowrap"><a className="btn-secondary !py-0.5 !px-2 mr-1" target="_blank" href={`${API}/v1/inventory/lots/${l.id}/labels.html?packKg=20&count=12&t=${getToken()}`}>Labels</a>{l.onHandKg > 0 && <><button className="btn-secondary !py-0.5 !px-2 mr-1" onClick={() => { setXfer(l); setXkg(0); setXto(''); }}>Transfer</button><button className="btn-secondary !py-0.5 !px-2" onClick={() => { setAdj(l); setAkg(0); }}>Adjust</button></>}</td></tr>)}</tbody></table></div>
    <Modal title="Goods receipt (GRN)" open={grn} onClose={() => setGrn(false)}><div className="grid grid-cols-2 gap-2">
      <Field label="Lot no"><input className="input" value={f.lotNo} onChange={(e) => setF({ ...f, lotNo: e.target.value })} /></Field>
      <Field label="Against PO (optional)"><select className="input" value={f.poId} onChange={(e) => { const po = pos?.find((p: any) => p.id === e.target.value); setF({ ...f, poId: e.target.value, ...(po ? { vendorId: po.vendorId, warehouseId: po.warehouseId, varietyId: po.lines[0]?.varietyId || f.varietyId, costRupees: (po.lines[0]?.ratePaisePerKg || 0) / 100 || f.costRupees } : {}) }); }}><option value="">— ad hoc —</option>{pos?.filter((p: any) => ['SENT', 'PARTIAL'].includes(p.status)).map((p: any) => <option key={p.id} value={p.id}>PO-{p.poNo} · {p.vendor.name}</option>)}</select></Field>
      <Field label="Vendor"><select className="input" value={f.vendorId} onChange={(e) => setF({ ...f, vendorId: e.target.value })}><option value="">Select</option>{vendors?.map((v: any) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></Field>
      <Field label="Warehouse"><select className="input" value={f.warehouseId} onChange={(e) => setF({ ...f, warehouseId: e.target.value })}><option value="">Select</option>{whs?.map((w: any) => <option key={w.id} value={w.id}>{w.code}</option>)}</select></Field>
      <Field label="Variety"><select className="input" value={f.varietyId} onChange={(e) => setF({ ...f, varietyId: e.target.value })}><option value="">Select</option>{cat?.items?.map((v: any) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></Field>
      <Field label="Harvest season"><input className="input" value={f.harvestSeason} onChange={(e) => setF({ ...f, harvestSeason: e.target.value })} /></Field>
      <Field label="Milled on"><input type="date" className="input" value={f.milledOn} onChange={(e) => setF({ ...f, milledOn: e.target.value })} /></Field>
      <Field label="Received kg"><input type="number" className="input" value={f.receivedKg} onChange={(e) => setF({ ...f, receivedKg: Number(e.target.value) })} /></Field>
      <Field label="Moisture % (spec <13)"><input type="number" step="0.1" className="input" value={f.moisturePct} onChange={(e) => setF({ ...f, moisturePct: Number(e.target.value) })} /></Field>
      <Field label="Brokens %"><input type="number" step="0.1" className="input" value={f.brokenPct} onChange={(e) => setF({ ...f, brokenPct: Number(e.target.value) })} /></Field>
      <Field label="Cost ₹/kg"><input type="number" step="0.5" className="input" value={f.costRupees} onChange={(e) => setF({ ...f, costRupees: Number(e.target.value) })} /></Field>
      <div className="col-span-2 text-xs text-gray-500">Bill of ₹{(f.costRupees * f.receivedKg).toLocaleString('en-IN')} will be posted to the vendor ledger with the vendor's payment terms.</div>
      <button className="btn-primary col-span-2" disabled={!f.vendorId || !f.warehouseId || !f.varietyId} onClick={submitGrn}>Receive</button></div></Modal>
    <Modal title={xfer ? `Transfer ${xfer.lotNo}` : ''} open={!!xfer} onClose={() => setXfer(null)}><div className="space-y-2"><Field label="To warehouse"><select className="input" value={xto} onChange={(e) => setXto(e.target.value)}><option value="">Select</option>{whs?.filter((w: any) => w.id !== xfer?.warehouseId).map((w: any) => <option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></Field><Field label={`Kg (max ${xfer?.onHandKg})`}><input type="number" className="input" value={xkg} onChange={(e) => setXkg(Number(e.target.value))} /></Field><button className="btn-primary w-full" disabled={!xto || xkg <= 0} onClick={submitXfer}>Transfer</button></div></Modal>
    <Modal title={adj ? `Adjust ${adj.lotNo}` : ''} open={!!adj} onClose={() => setAdj(null)}><div className="space-y-2"><Field label="Reason"><select className="input" value={areason} onChange={(e) => setAreason(e.target.value)}><option value="DAMAGE">Damage / pest write-off (−)</option><option value="ADJUST">Count correction (±)</option></select></Field><Field label="Kg"><input type="number" className="input" value={akg} onChange={(e) => setAkg(Number(e.target.value))} /></Field><Field label="Note"><input className="input" value={anote} onChange={(e) => setAnote(e.target.value)} /></Field><button className="btn-primary w-full" onClick={submitAdj}>Apply</button></div></Modal></div>;
}
