#!/usr/bin/env bash
# One-time: populate the PostgreSQL schema + demo data for Aetos One Cloud.
# Wraps ThingsBoard's own install_dev_db.sh (generated by the Maven build).
set -euo pipefail

TB="/run/media/krishna/data-backup/claude-cowork/AetosOne-TB/thingsboard"
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
export PATH="$JAVA_HOME/bin:$PATH"
export SPRING_DATASOURCE_PASSWORD=postgres

echo "==> recreating database 'thingsboard'"
sudo -u postgres psql -q -c "DROP DATABASE IF EXISTS thingsboard;"
sudo -u postgres psql -q -c "CREATE DATABASE thingsboard;"

echo "==> running ThingsBoard dev DB installer"
cd "$TB/application/target/bin/install"
./install_dev_db.sh

echo
echo "Default logins:"
echo "  sysadmin@thingsboard.org / sysadmin"
echo "  tenant@thingsboard.org   / tenant"
echo "  customer@thingsboard.org / customer"
