-- Every *_at column was created as `timestamp` (no time zone). Postgres stored the
-- server's local wall-clock value and postgres-js read it back tagged as UTC, so every
-- date in the product was skewed by the server's offset (IST: 5h30m into the future —
-- a just-contacted customer rendered as "-313m ago"). The same skew silently applied to
-- SLA deadlines, appointment reminders, campaign schedules and billing periods.
--
-- Existing values were written as Asia/Kolkata wall-clock, so that is the zone they are
-- reinterpreted from. AT TIME ZONE on a naive timestamp reads it AS that zone and yields
-- the correct absolute instant.

ALTER TABLE "ad_campaigns" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "ad_campaigns" ALTER COLUMN "scheduled_at" TYPE timestamptz USING "scheduled_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "api_keys" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "api_keys" ALTER COLUMN "last_used_at" TYPE timestamptz USING "last_used_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "api_keys" ALTER COLUMN "revoked_at" TYPE timestamptz USING "revoked_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "appointments" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "appointments" ALTER COLUMN "reminder_sent_at" TYPE timestamptz USING "reminder_sent_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "appointments" ALTER COLUMN "starts_at" TYPE timestamptz USING "starts_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "appointments" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "automation_rules" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "automation_rules" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "bots" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "campaign_recipients" ALTER COLUMN "next_send_at" TYPE timestamptz USING "next_send_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "campaign_recipients" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "campaigns" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "campaigns" ALTER COLUMN "scheduled_at" TYPE timestamptz USING "scheduled_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "canned_responses" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "channels" ALTER COLUMN "connected_at" TYPE timestamptz USING "connected_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "companies" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "contacts" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "contacts" ALTER COLUMN "last_contacted_at" TYPE timestamptz USING "last_contacted_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "conversation_charges" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "conversation_charges" ALTER COLUMN "window_end" TYPE timestamptz USING "window_end" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "conversation_charges" ALTER COLUMN "window_start" TYPE timestamptz USING "window_start" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "conversation_notes" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "conversation_rates" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "conversations" ALTER COLUMN "last_message_at" TYPE timestamptz USING "last_message_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "conversations" ALTER COLUMN "service_window_expires_at" TYPE timestamptz USING "service_window_expires_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "dashboard_layouts" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "deals" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "deals" ALTER COLUMN "expected_close_date" TYPE timestamptz USING "expected_close_date" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "deals" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "distribution_rules" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "flow_responses" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "flows" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "flows" ALTER COLUMN "published_at" TYPE timestamptz USING "published_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "flows" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "invites" ALTER COLUMN "accepted_at" TYPE timestamptz USING "accepted_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "invites" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "invites" ALTER COLUMN "expires_at" TYPE timestamptz USING "expires_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "lead_scoring_rules" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "license_activations" ALTER COLUMN "first_seen_at" TYPE timestamptz USING "first_seen_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "license_activations" ALTER COLUMN "last_seen_at" TYPE timestamptz USING "last_seen_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "license_activations" ALTER COLUMN "revoked_at" TYPE timestamptz USING "revoked_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "licenses" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "licenses" ALTER COLUMN "valid_from" TYPE timestamptz USING "valid_from" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "licenses" ALTER COLUMN "valid_until" TYPE timestamptz USING "valid_until" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "messages" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "orgs" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "orgs" ALTER COLUMN "plan_renews_at" TYPE timestamptz USING "plan_renews_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "partner_invites" ALTER COLUMN "accepted_at" TYPE timestamptz USING "accepted_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "partner_invites" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "partner_invites" ALTER COLUMN "expires_at" TYPE timestamptz USING "expires_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "partner_members" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "partners" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "partners" ALTER COLUMN "domain_verified_at" TYPE timestamptz USING "domain_verified_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "pipelines" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "quotes" ALTER COLUMN "accepted_at" TYPE timestamptz USING "accepted_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "quotes" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "quotes" ALTER COLUMN "sent_at" TYPE timestamptz USING "sent_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "quotes" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "quotes" ALTER COLUMN "valid_until" TYPE timestamptz USING "valid_until" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "refresh_tokens" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "refresh_tokens" ALTER COLUMN "expires_at" TYPE timestamptz USING "expires_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "refresh_tokens" ALTER COLUMN "revoked_at" TYPE timestamptz USING "revoked_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "saved_views" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "social_posts" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "social_posts" ALTER COLUMN "scheduled_at" TYPE timestamptz USING "scheduled_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "survey_responses" ALTER COLUMN "answered_at" TYPE timestamptz USING "answered_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "survey_responses" ALTER COLUMN "sent_at" TYPE timestamptz USING "sent_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "surveys" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "tasks" ALTER COLUMN "completed_at" TYPE timestamptz USING "completed_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "tasks" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "tasks" ALTER COLUMN "due_at" TYPE timestamptz USING "due_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "teams" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "templates" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "ticket_events" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "ticket_rules" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "tickets" ALTER COLUMN "closed_at" TYPE timestamptz USING "closed_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "tickets" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "tickets" ALTER COLUMN "first_response_at" TYPE timestamptz USING "first_response_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "tickets" ALTER COLUMN "resolved_at" TYPE timestamptz USING "resolved_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "tickets" ALTER COLUMN "sla_due_at" TYPE timestamptz USING "sla_due_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "tickets" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "users" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "wallet_transactions" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "webhook_deliveries" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "webhook_deliveries" ALTER COLUMN "delivered_at" TYPE timestamptz USING "delivered_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "webhook_deliveries" ALTER COLUMN "next_attempt_at" TYPE timestamptz USING "next_attempt_at" AT TIME ZONE 'Asia/Kolkata';
ALTER TABLE "webhook_endpoints" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at" AT TIME ZONE 'Asia/Kolkata';
