'use client';
import { useState } from 'react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import { api } from '@/lib/api';
import { Grain, GrainField, Counter, Reveal, Section, fadeUp, Journey, BagLabel } from '@/components/graphics';

const VARIETIES = [{ n: 'Sona Masoori', t: 'సోనా మసూరి', d: 'The daily staple. Aged 6–12 months so it cooks fluffy, not sticky.', c: 'from-amber-100 to-amber-50' }, { n: 'HMT', t: 'హెచ్‌ఎంటీ', d: 'Fine grain, soft texture — Warangal\'s favourite.', c: 'from-lime-100 to-lime-50' }, { n: 'BPT 5204', t: 'బీపీటీ', d: 'Slightly sticky, great for pulihora and curd rice.', c: 'from-emerald-100 to-emerald-50' }, { n: 'Basmati 1121', t: 'బాస్మతి', d: 'Steam basmati for biryani weekends. Fresh milled.', c: 'from-orange-100 to-orange-50' }, { n: 'Brown rice', t: 'బ్రౌన్ రైస్', d: 'Unpolished, low-GI, for the health-conscious.', c: 'from-stone-200 to-stone-50' }];
const STEPS = [['Pick your rice', 'Variety, pack size and how often — every 3 weeks is the household favourite.'], ['We message you the night before', 'Reply SKIP if you\'re away. No app needed.'], ['Bag arrives, OTP handover', 'Carried up to your kitchen. Lot label on every bag.'], ['Refer a neighbour', '₹100 in your wallet the moment their first bag is delivered.']];
const QUOTES = ['"First time rice came with the milling date. My mother approved." — Lakshmi, KPHB', '"25 kg to the 4th floor, no lift, on time. Every week." — Suresh, Ameerpet PG', '"Aged Sona Masoori that actually tastes like the village rice." — Padma, Madhapur', '"WhatsApp SKIP when we travel. That\'s it." — Ravi, Gachibowli'];

// Each card links to where the feature actually lives. The trace links open a real lot so visitors see live numbers.
const FEATURES = [
  { i: '🍚', t: 'Cook mode for your exact lot', d: 'Rice : water ratio, soak time and cooker whistles worked out from that lot’s real age and moisture. A 7-month lot at 12.8 % moisture says 1 : 1.9, 20 min soak, 3 whistles.', h: '/trace/LOT-SONA-2508-02', c: 'See a live lot' },
  { i: '🏭', t: 'From the mill, in their words', d: 'The mill that milled your bag writes its own story and photo. It appears on every trace page for their lots — the lot number on your bag is theirs.', h: '/trace/LOT-SONA-2508-02', c: 'Read Sri Balaji’s' },
  { i: '⚖️', t: 'Compare your supermarket bag', d: 'Type the packed-on date and MRP from the bag you have at home. We show how old it is at minimum and what you pay per kg vs ours.', h: '/trace/LOT-SONA-2508-02', c: 'Try the comparison' },
  { i: '📏', t: 'Household rice meter', d: 'On your account page: how much of the last bag is left, the day it runs out, and one tap to put the right pack back in the cart. Learns your pace after 3 weeks.', h: '/shop/account', c: 'Open my account' },
  { i: '🎂', t: 'Your rice’s birthday', d: 'A WhatsApp when a bag you bought crosses 6 months (it’s in the sweet spot now) and again past 12 (time for a fresher lot). Once per bag, never spam.', h: '/shop/orders', c: 'My orders' },
  { i: '🔍', t: 'Every scan is watched', d: 'Each QR scan is logged. If one lot code starts showing up from many different phones — or a code we never printed — our ops desk sees it in red the same day.', h: '/trace/LOT-SONA-2508-02', c: 'Scan a real label' },
];

export default function Landing() {
  const [pin, setPin] = useState(''); const [res, setRes] = useState<any>(null); const [checking, setChecking] = useState(false);
  const check = async () => { setChecking(true); try { setRes(await api('/zones/check?pincode=' + pin)); } catch (e: any) { setRes({ error: e.message }); } finally { setChecking(false); } };
  return <main className="min-h-screen overflow-x-hidden">
    <header className="absolute top-0 inset-x-0 z-20 text-white"><div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between"><motion.div initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} className="font-bold text-lg flex items-center gap-2"><Grain size={14} /> FreshRice</motion.div><nav className="flex gap-5 text-sm">{[['/shop', 'Shop'], ['/b2b', 'Business'], ['/login', 'Login']].map(([h, l], i) => <motion.div key={h} initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 * i }}><Link href={h} className="hover:underline underline-offset-4">{l}</Link></motion.div>)}</nav></div></header>

    {/* HERO */}
    <section className="hero-bg relative text-white pt-28 pb-20 px-4"><GrainField />
      <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-10 items-center relative">
        <div><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="glass inline-block rounded-full px-3 py-1 text-xs mb-4">🌾 Telangana mills → Hyderabad kitchens · 24 h</motion.div>
          <Reveal text="Mill-direct rice. Correctly aged. Every bag traceable." className="text-4xl md:text-5xl font-black leading-[1.08]" />
          <motion.p variants={fadeUp} initial="hidden" animate="show" transition={{ delay: 0.8 }} className="mt-5 text-white/85 text-lg max-w-lg">Sona Masoori, HMT and BPT straight from Miryalaguda and Warangal, aged the way Hyderabad kitchens want it — with the harvest, milling date, mill and moisture printed on the bag. Delivered up the stairs.</motion.p>
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1 }} className="mt-7 flex gap-2 max-w-md"><input className="input !py-3 !text-base text-gray-900" placeholder="Your pincode" value={pin} maxLength={6} inputMode="numeric" onChange={(e) => setPin(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && check()} /><motion.button whileTap={{ scale: 0.96 }} whileHover={{ scale: 1.03 }} className="btn bg-white text-leaf-700 !py-3 px-5 font-bold" onClick={check} disabled={pin.length !== 6 || checking}>{checking ? '…' : 'Check'}</motion.button></motion.div>
          <AnimatePresence>{res && <motion.div key={JSON.stringify(res)} initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }} className="mt-3 text-sm">{res.error ? <span className="text-red-200">{res.error}</span> : res.serviceable ? <motion.span initial={{ scale: 0.9 }} animate={{ scale: 1 }} className="glass inline-flex items-center gap-2 rounded-full px-3 py-1.5"><motion.span animate={{ rotate: [0, 20, -10, 0] }} transition={{ duration: 0.6 }}>✅</motion.span> We deliver in {res.zone.name}. <Link href={'/shop?pincode=' + pin} className="underline font-semibold">Shop now →</Link></motion.span> : <span className="glass inline-block rounded-full px-3 py-1.5">Not yet — you're on the waitlist for {pin}. We open new zones every month.</span>}</motion.div>}</AnimatePresence>
          <div className="mt-9 grid grid-cols-3 gap-3 max-w-md">{[[20, '%', 'cheaper than quick-commerce'], [24, ' h', 'from zone warehouse'], [0, '', 'middlemen']].map(([v, s, l], i) => <motion.div key={i} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.2 + i * 0.15 }} className="glass rounded-xl p-3"><div className="text-2xl font-black"><Counter to={v as number} suffix={s as string} /></div><div className="text-xs text-white/80">{l}</div></motion.div>)}</div></div>
        <div className="relative"><BagLabel /><motion.div className="absolute -bottom-6 -left-4 glass rounded-xl px-3 py-2 text-xs" initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 1.4 }}>🛺 Rider 3 stops away · OTP 4821</motion.div><motion.div className="absolute -top-4 -right-2 glass rounded-xl px-3 py-2 text-xs" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 1.6 }}>💬 “Reply SKIP to skip”</motion.div></div></div>
      <svg className="absolute bottom-0 left-0 w-full" viewBox="0 0 1440 60" preserveAspectRatio="none"><path d="M0 60 C 360 0, 1080 0, 1440 60 Z" fill="#fbf8f1" /></svg></section>

    {/* JOURNEY */}
    <Section className="max-w-5xl mx-auto px-4 py-16"><motion.h2 variants={fadeUp} className="text-3xl font-bold text-center">From the mill to your kitchen, nothing in between</motion.h2><motion.p variants={fadeUp} className="text-center text-gray-600 mt-2 max-w-2xl mx-auto">No wholesaler, no distributor, no kirana markup. We buy at the mill, check every lot for moisture and brokens, and bring it to your door in our own vehicles.</motion.p><motion.div variants={fadeUp} className="mt-8 card !p-2 md:!p-6"><Journey /></motion.div></Section>

    {/* WHY AGED */}
    <Section className="bg-white border-y"><div className="max-w-5xl mx-auto px-4 py-16 grid md:grid-cols-2 gap-10 items-center">
      <motion.div variants={fadeUp}><div className="text-xs uppercase tracking-widest text-rice-700 font-semibold">What fresh really means</div><h2 className="text-3xl font-bold mt-2">Freshly milled. Never new-crop.</h2><p className="text-gray-600 mt-3">Fresh rice is rice milled to order from properly aged paddy — not rice from this season's harvest. New-crop Sona Masoori absorbs too much water and cooks sticky. Telangana households have always waited for rice to age 6–12 months. Supermarkets don't tell you the age. We print it — and we only ship Sona Masoori, HMT and BPT that has aged at least 6 months.</p><div className="mt-5 flex gap-3 text-sm"><Link href="/shop" className="btn-primary">See today's lots</Link><a href="#how" className="btn-secondary">How subscriptions work</a></div></motion.div>
      <motion.div variants={fadeUp} className="grid grid-cols-2 gap-3">{[['New-crop rice', '0–3 mo', 'Sticky, mushy, low yield', 'bg-red-50 border-red-200'], ['Aged & freshly milled', '6–12 mo', 'Fluffy, separate grains, more cups per kg', 'bg-green-50 border-green-200']].map(([t, a, d, c]) => <motion.div key={t} whileHover={{ y: -4 }} className={'rounded-2xl border p-4 ' + c}><div className="font-bold">{t}</div><div className="text-3xl font-black my-1">{a}</div><div className="text-xs text-gray-600">{d}</div></motion.div>)}<div className="col-span-2 rounded-2xl bg-rice-100 p-4 text-sm"><b>What's on every bag:</b> harvest season · milling date · aged months · mill name · moisture % · brokens % · lot QR.</div></motion.div></div></Section>

    {/* VARIETIES */}
    <Section className="max-w-6xl mx-auto px-4 py-16"><motion.h2 variants={fadeUp} className="text-3xl font-bold text-center">What's in the warehouse this week</motion.h2>
      <div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-5 gap-4">{VARIETIES.map((v, i) => <motion.div key={v.n} variants={fadeUp} whileHover={{ y: -6, rotate: i % 2 ? 0.6 : -0.6 }} className={'rounded-2xl bg-gradient-to-b p-4 border border-white shadow-sm ' + v.c}><motion.div animate={{ rotate: [0, 6, -6, 0] }} transition={{ duration: 5, repeat: Infinity, delay: i * 0.4 }} className="w-fit"><Grain size={26} /></motion.div><div className="font-bold mt-2">{v.n}</div><div className="text-xs text-gray-500">{v.t}</div><div className="text-sm text-gray-700 mt-2">{v.d}</div></motion.div>)}</div>
      <motion.div variants={fadeUp} className="text-center mt-6"><Link href="/shop" className="btn-primary">Open the shop →</Link></motion.div></Section>

    {/* WITH EVERY BAG — the traceability + household features, each linked to where it lives */}
    <Section className="bg-white border-y"><div className="max-w-6xl mx-auto px-4 py-16">
      <motion.div variants={fadeUp} className="text-xs uppercase tracking-widest text-rice-700 font-semibold text-center">More than rice</motion.div>
      <motion.h2 variants={fadeUp} className="text-3xl font-bold text-center mt-2">What comes with every bag</motion.h2>
      <motion.p variants={fadeUp} className="text-center text-gray-600 mt-2 max-w-2xl mx-auto">Scan the QR on the label. Everything below is worked out from <em>that</em> lot — its real age, moisture and mill — not a generic chart.</motion.p>
      <div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{FEATURES.map((f, i) => <motion.div key={f.t} variants={fadeUp} whileHover={{ y: -4 }} className="card flex flex-col"><div className="text-3xl">{f.i}</div><div className="font-bold mt-2">{f.t}</div><div className="text-sm text-gray-600 mt-1 flex-1">{f.d}</div><Link href={f.h} className="text-sm font-semibold text-leaf-700 mt-3 underline underline-offset-2">{f.c} →</Link></motion.div>)}</div>
    </div></Section>

    {/* HOW */}
    <Section className="bg-leaf-700 text-white"><div id="how" className="max-w-5xl mx-auto px-4 py-16"><motion.h2 variants={fadeUp} className="text-3xl font-bold">Set it and forget it</motion.h2>
      <div className="mt-8 grid md:grid-cols-4 gap-4">{STEPS.map(([t, d], i) => <motion.div key={t} variants={fadeUp} className="relative glass rounded-2xl p-4"><motion.div className="absolute -top-3 -left-2 w-8 h-8 rounded-full bg-white text-leaf-700 font-black grid place-items-center" initial={{ scale: 0 }} whileInView={{ scale: 1 }} viewport={{ once: true }} transition={{ delay: 0.3 + i * 0.15, type: 'spring' }}>{i + 1}</motion.div><div className="font-bold mt-2">{t}</div><div className="text-sm text-white/80 mt-1">{d}</div></motion.div>)}</div>
      <motion.div variants={fadeUp} className="mt-8 grid grid-cols-2 md:grid-cols-4 gap-4 text-center">{[[500, '+', 'tonnes/day Hyderabad eats'], [12, '', 'pincodes live'], [6, '+ mo', 'minimum ageing'], [100, '₹', 'per referral']].map(([v, s, l], i) => <div key={i}><div className="text-3xl font-black"><Counter to={v as number} suffix={s === '₹' ? '' : (s as string)} prefix={s === '₹' ? '₹' : ''} /></div><div className="text-xs text-white/75">{l}</div></div>)}</motion.div></div></Section>

    {/* QUOTES MARQUEE */}
    <div className="py-10 overflow-hidden bg-white border-y"><div className="marquee">{[...QUOTES, ...QUOTES].map((q, i) => <div key={i} className="card min-w-[320px] text-sm text-gray-700">{q}</div>)}</div></div>

    {/* B2B + CTA */}
    <Section className="max-w-5xl mx-auto px-4 py-16 grid md:grid-cols-2 gap-6">
      <motion.div variants={fadeUp} className="card bg-gradient-to-br from-white to-rice-100"><div className="text-xs uppercase tracking-widest text-rice-700 font-semibold">PGs · hostels · restaurants</div><h3 className="text-2xl font-bold mt-1">Bulk, prepaid, invoiced.</h3><p className="text-sm text-gray-600 mt-2">25 kg and 50 kg packs at tier pricing, GST tax invoices, early-morning windows. Pay on delivery or UPI — no credit, no paperwork.</p><Link href="/b2b" className="btn-secondary mt-4">Open a business account</Link></motion.div>
      <motion.div variants={fadeUp} className="card bg-gradient-to-br from-leaf-600 to-leaf-700 text-white"><div className="text-xs uppercase tracking-widest text-white/70 font-semibold">Refer a neighbour</div><h3 className="text-2xl font-bold mt-1">₹100 for you, ₹100 for them.</h3><p className="text-sm text-white/85 mt-2">Share your code on the society WhatsApp group. The moment their first bag is delivered, your wallet is credited — in real time.</p><Link href="/login" className="btn bg-white text-leaf-700 mt-4 font-bold">Get my code</Link></motion.div></Section>

    <footer className="text-xs text-gray-500 text-center py-8">FreshRice · Kukatpally, Hyderabad · FSSAI 13626000000000 · <a className="underline" href="https://wa.me/919000000001">WhatsApp us</a></footer>
  </main>;
}
