'use client';
import { useState } from 'react';
import useSWR from 'swr';
import { api, fetcher, paise, fmtDate, tomorrow } from '@/lib/api';
import { Modal, Field, useToast, StatusBadge } from '@/components/ui';
export default function POs() {
  const { data, mutate } = useSWR('/admin/purchase-orders', fetcher); const { data: vendors } = useSWR('/admin/vendors', fetcher); const { data: whs } = useSWR('/admin/warehouses', fetcher); const { data: cat } = useSWR('/catalog', fetcher); const { show, Toast } = useToast();
  const [open, setOpen] = useState(false); const [f, setF] = useState<any>({ vendorId: '', warehouseId: '', expectedOn: tomorrow(), notes: '', lines: [{ varietyId: '', kg: 2000, rateRupeesPerKg: 44 }] });
  const total = f.lines.reduce((a: number, l: any) => a + l.kg * l.rateRupeesPerKg, 0);
  const create = async () => { try { await api('/admin/purchase-orders', { body: f }); setOpen(false); mutate(); show('PO sent'); } catch (e: any) { show(e.message, true); } };
  const setStatus = async (id: string, status: string) => { await api('/admin/purchase-orders/' + id, { method: 'PATCH', body: { status } }); mutate(); };
  return <div><Toast /><div className="flex justify-between items-center mb-4"><h1 className="text-2xl font-bold">Purchase orders</h1><button className="btn-primary" onClick={() => setOpen(true)}>+ New PO</button></div>
    <p className="text-sm text-gray-600 mb-3">Raise a PO to a mill, then receive it via GRN on the Stock page — received kg tracks against each line and the vendor bill posts automatically.</p>
    <div className="card overflow-auto"><table className="tbl"><thead><tr><th>PO</th><th>Vendor</th><th>Warehouse</th><th>Expected</th><th>Lines</th><th className="text-right">Value</th><th>Status</th><th></th></tr></thead><tbody>
      {data?.map((p: any) => <tr key={p.id}><td>PO-{p.poNo}<br /><small>{fmtDate(p.createdAt)}</small></td><td>{p.vendor.name}</td><td>{p.warehouse.code}</td><td>{fmtDate(p.expectedOn)}</td><td className="text-xs">{p.lines.map((l: any) => <div key={l.id}>{l.variety.name}: {l.receivedKg}/{l.kg} kg @ {paise(l.ratePaisePerKg)}</div>)}</td><td className="text-right">{paise(p.totalPaise)}</td><td><StatusBadge s={p.status} /></td><td className="text-xs">{['SENT', 'PARTIAL', 'RECEIVED'].includes(p.status) && <button className="btn-secondary !py-0.5 !px-2 mr-1" onClick={() => setStatus(p.id, 'CLOSED')}>Close</button>}{p.status === 'SENT' && <button className="btn-secondary !py-0.5 !px-2" onClick={() => setStatus(p.id, 'CANCELLED')}>Cancel</button>}</td></tr>)}</tbody></table></div>
    <Modal title="New purchase order" open={open} onClose={() => setOpen(false)}><div className="space-y-2">
      <div className="grid grid-cols-2 gap-2"><Field label="Vendor"><select className="input" value={f.vendorId} onChange={(e) => setF({ ...f, vendorId: e.target.value })}><option value="">Select</option>{vendors?.filter((v: any) => v.active).map((v: any) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></Field><Field label="Deliver to warehouse"><select className="input" value={f.warehouseId} onChange={(e) => setF({ ...f, warehouseId: e.target.value })}><option value="">Select</option>{whs?.map((w: any) => <option key={w.id} value={w.id}>{w.code}</option>)}</select></Field><Field label="Expected on"><input type="date" className="input" value={f.expectedOn} onChange={(e) => setF({ ...f, expectedOn: e.target.value })} /></Field><Field label="Notes"><input className="input" value={f.notes} onChange={(e) => setF({ ...f, notes: e.target.value })} placeholder="moisture <13%, brokens <3%" /></Field></div>
      {f.lines.map((l: any, i: number) => <div key={i} className="grid grid-cols-3 gap-2"><select className="input" value={l.varietyId} onChange={(e) => { const lines = [...f.lines]; lines[i] = { ...l, varietyId: e.target.value }; setF({ ...f, lines }); }}><option value="">Variety</option>{cat?.items?.map((v: any) => <option key={v.id} value={v.id}>{v.name}</option>)}</select><input type="number" className="input" placeholder="kg" value={l.kg} onChange={(e) => { const lines = [...f.lines]; lines[i] = { ...l, kg: Number(e.target.value) }; setF({ ...f, lines }); }} /><input type="number" step="0.5" className="input" placeholder="₹/kg" value={l.rateRupeesPerKg} onChange={(e) => { const lines = [...f.lines]; lines[i] = { ...l, rateRupeesPerKg: Number(e.target.value) }; setF({ ...f, lines }); }} /></div>)}
      <button className="btn-secondary" onClick={() => setF({ ...f, lines: [...f.lines, { varietyId: '', kg: 1000, rateRupeesPerKg: 44 }] })}>+ line</button>
      <div className="text-right font-semibold">Total ₹{total.toLocaleString('en-IN')}</div>
      <button className="btn-primary w-full" disabled={!f.vendorId || !f.warehouseId || f.lines.some((l: any) => !l.varietyId)} onClick={create}>Send PO</button></div></Modal></div>;
}
