'use client';
import { useState } from 'react';
import useSWR from 'swr';
import { fetcher, paise, fmtDate, ymd, API, getToken } from '@/lib/api';
export default function Reports() {
  const [from, setFrom] = useState(ymd(new Date(Date.now() - 29 * 86400000))); const [to, setTo] = useState(ymd(new Date())); const [tab, setTab] = useState('daily');
  const q = `?from=${from}&to=${to}`;
  const { data } = useSWR(`/admin/reports/${tab}${['daily', 'zones', 'gst'].includes(tab) ? q : ''}`, fetcher);
  const dl = (name: string, format: 'csv' | 'xlsx' | 'pdf') => { fetch(`${API}/v1/admin/reports/${name}${q}&format=${format}`, { headers: { Authorization: 'Bearer ' + getToken() } }).then((r) => r.blob()).then((b) => { const a = document.createElement('a'); a.href = URL.createObjectURL(b); a.download = `${name}-${from}-${to}.${format}`; a.click(); }); };
  const ExportBtns = () => <div className="flex gap-1 items-center"><span className="text-xs text-gray-500 mr-1">Export</span>{(['csv', 'xlsx', 'pdf'] as const).map((f) => <button key={f} className="btn-secondary !py-1 !px-2 uppercase text-xs" onClick={() => dl(tab, f)}>{f}</button>)}</div>;
  const tabs = [['daily', 'Daily sales'], ['zones', 'Zone economics'], ['gst', 'GST'], ['payables', 'Vendor payables'], ['stock-valuation', 'Stock valuation'], ['cohorts', 'Customer cohorts']];
  return <div><div className="flex justify-between items-center mb-4 flex-wrap gap-2"><h1 className="text-2xl font-bold">Reports</h1><div className="flex gap-2 items-center"><input type="date" className="input" value={from} onChange={(e) => setFrom(e.target.value)} /><span>→</span><input type="date" className="input" value={to} onChange={(e) => setTo(e.target.value)} /><ExportBtns /><a className="btn-secondary" href="/admin/data">Import / bulk export</a></div></div>
    <div className="flex gap-1 mb-4 flex-wrap">{tabs.map(([k, l]) => <button key={k} className={'btn ' + (tab === k ? 'bg-leaf-600 text-white' : 'bg-white border')} onClick={() => setTab(k)}>{l}</button>)}</div>
    <div className="card overflow-auto">
      {tab === 'daily' && <table className="tbl"><thead><tr><th>Date</th><th>Orders</th><th>Delivered</th><th>Cancelled</th><th className="text-right">Revenue</th><th className="text-right">kg</th><th className="text-right">GST</th><th className="text-right">COGS</th><th className="text-right">GM %</th></tr></thead><tbody>{data?.map((r: any) => <tr key={r.date}><td>{r.date}</td><td>{r.orders}</td><td>{r.delivered}</td><td>{r.cancelled}</td><td className="text-right">{paise(r.revenuePaise)}</td><td className="text-right">{Math.round(r.kg)}</td><td className="text-right">{paise(r.gstPaise)}</td><td className="text-right">{paise(r.cogsPaise)}</td><td className="text-right">{r.grossMarginPct ?? '—'}</td></tr>)}</tbody></table>}
      {tab === 'zones' && <table className="tbl"><thead><tr><th>Zone</th><th>Orders</th><th>Delivered</th><th>Failed</th><th>On-time %</th><th className="text-right">Revenue</th><th className="text-right">kg</th><th>Customers</th><th>Routes</th><th>Drops/route</th><th className="text-right">Est. cost/drop</th></tr></thead><tbody>{data?.map((r: any) => <tr key={r.zone}><td>{r.zone}</td><td>{r.orders}</td><td>{r.delivered}</td><td>{r.failed}</td><td>{r.onTimePct ?? '—'}</td><td className="text-right">{paise(r.revenuePaise)}</td><td className="text-right">{Math.round(r.kg)}</td><td>{r.customers}</td><td>{r.routes}</td><td>{r.dropsPerRoute ?? '—'}</td><td className="text-right">{r.deliveryCostPerDropPaise ? paise(r.deliveryCostPerDropPaise) : '—'}</td></tr>)}</tbody></table>}
      {tab === 'gst' && data && <><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3 text-sm">{[['Invoices', data.summary.invoices], ['Taxable', '₹' + data.summary.taxable.toLocaleString('en-IN')], ['CGST + SGST', '₹' + (data.summary.cgst + data.summary.sgst).toLocaleString('en-IN')], ['B2B invoices', data.summary.b2b]].map(([l, v]) => <div key={l as string} className="card"><div className="text-xs text-gray-500">{l}</div><b className="text-lg">{v}</b></div>)}</div><table className="tbl"><thead><tr><th>Invoice</th><th>Date</th><th>Order</th><th>Buyer</th><th>GSTIN</th><th className="text-right">Taxable</th><th className="text-right">CGST</th><th className="text-right">SGST</th><th className="text-right">Total</th></tr></thead><tbody>{data.rows.map((r: any) => <tr key={r.invoiceNo}><td className="font-mono text-xs">{r.invoiceNo}</td><td>{r.date}</td><td>#{r.orderNo}</td><td>{r.buyer}</td><td className="font-mono text-xs">{r.buyerGstin}</td><td className="text-right">₹{r.taxable}</td><td className="text-right">₹{r.cgst}</td><td className="text-right">₹{r.sgst}</td><td className="text-right">₹{r.total}</td></tr>)}</tbody></table></>}
      {tab === 'payables' && <table className="tbl"><thead><tr><th>Vendor</th><th>Type</th><th className="text-right">Billed</th><th className="text-right">Paid</th><th className="text-right">Outstanding</th><th className="text-right">Overdue</th><th>Next due</th></tr></thead><tbody>{data?.map((r: any) => <tr key={r.vendor}><td>{r.vendor}</td><td>{r.type}</td><td className="text-right">{paise(r.billedPaise)}</td><td className="text-right">{paise(r.paidPaise)}</td><td className="text-right font-semibold">{paise(r.outstandingPaise)}</td><td className={'text-right ' + (r.overduePaise > 0 ? 'text-red-600' : '')}>{paise(r.overduePaise)}</td><td>{r.nextDue ? fmtDate(r.nextDue) : '—'}</td></tr>)}</tbody></table>}
      {tab === 'stock-valuation' && <table className="tbl"><thead><tr><th>Warehouse</th><th>Variety</th><th className="text-right">kg</th><th className="text-right">Value (cost)</th><th>Lots</th><th>Oldest milled</th></tr></thead><tbody>{data?.map((r: any, i: number) => <tr key={i}><td>{r.warehouse}</td><td>{r.variety}</td><td className="text-right">{Math.round(r.kg)}</td><td className="text-right">{paise(r.valuePaise)}</td><td>{r.lots}</td><td>{fmtDate(r.oldestMilledOn)}</td></tr>)}</tbody></table>}
      {tab === 'cohorts' && <table className="tbl"><thead><tr><th>Cohort (first delivery month)</th><th>Customers</th><th>Repeat %</th><th>Orders / customer</th><th className="text-right">Revenue</th></tr></thead><tbody>{data?.map((r: any) => <tr key={r.cohort}><td>{r.cohort}</td><td>{r.customers}</td><td>{r.repeatPct}%</td><td>{r.ordersPerCustomer}</td><td className="text-right">{paise(r.revenuePaise)}</td></tr>)}</tbody></table>}
      {data && Array.isArray(data) && !data.length && <div className="text-gray-400 text-center py-6">No data in range</div>}
    </div></div>;
}
