'use client';
import { useState } from 'react';
import useSWR from 'swr';
import { api, fetcher, paise, fmtDate } from '@/lib/api';
import { Modal, Field, useToast } from '@/components/ui';
export default function Customers() {
  const [q, setQ] = useState(''); const { data, mutate } = useSWR('/admin/customers?q=' + encodeURIComponent(q), fetcher); const { show, Toast } = useToast(); const [rider, setRider] = useState<any>(null); const { data: riders, mutate: mR } = useSWR('/admin/riders', fetcher);
  return <div><Toast /><div className="flex justify-between items-center mb-4"><h1 className="text-2xl font-bold">Customers</h1><div className="flex gap-2"><input className="input" placeholder="Search name / phone" value={q} onChange={(e) => setQ(e.target.value)} /><button className="btn-secondary" onClick={() => setRider({ phone: '', name: '' })}>+ Add rider</button></div></div>
    <div className="card overflow-auto mb-4"><table className="tbl"><thead><tr><th>Name</th><th>Phone</th><th>Role</th><th>Zone</th><th>Orders</th><th>Subs</th><th>Last order</th><th>Wallet</th><th>Referral</th><th></th></tr></thead><tbody>
      {data?.map((u: any) => { const last = u.orders[0]; const days = last ? Math.floor((Date.now() - new Date(last.createdAt).getTime()) / 86400000) : null; return <tr key={u.id}><td>{u.name || '—'}{u.b2bAccount && <div className="text-xs text-gray-500">{u.b2bAccount.name}</div>}</td><td>{u.phone}</td><td><span className="badge bg-gray-100">{u.role}</span></td><td>{u.addresses[0]?.zone?.name || '—'}</td><td>{u._count.orders}</td><td>{u._count.subscriptions}</td><td className={days !== null && days > 35 ? 'text-red-600 font-medium' : ''}>{last ? `${fmtDate(last.createdAt)} (${days}d)` : '—'}</td><td>{paise(u.walletBalance)}</td><td className="font-mono text-xs">{u.referralCode}</td>
        <td><select className="input !py-0.5 text-xs" value={u.role} onChange={async (e) => { await api(`/admin/users/${u.id}/role`, { method: 'PATCH', body: { role: e.target.value } }); mutate(); show('Role updated'); }}>{['CUSTOMER', 'B2B_USER', 'RIDER', 'OPS', 'ADMIN'].map((r) => <option key={r}>{r}</option>)}</select></td></tr>; })}</tbody></table></div>
    <h2 className="font-semibold mb-2">Riders</h2><div className="card"><table className="tbl"><thead><tr><th>Name</th><th>Phone</th></tr></thead><tbody>{riders?.map((r: any) => <tr key={r.id}><td>{r.name}</td><td>{r.phone}</td></tr>)}</tbody></table></div>
    <Modal title="Add rider" open={!!rider} onClose={() => setRider(null)}>{rider && <div className="space-y-2"><Field label="Name"><input className="input" value={rider.name} onChange={(e) => setRider({ ...rider, name: e.target.value })} /></Field><Field label="Mobile"><input className="input" value={rider.phone} onChange={(e) => setRider({ ...rider, phone: e.target.value })} /></Field><button className="btn-primary w-full" onClick={async () => { await api('/admin/riders', { body: rider }); mR(); mutate(); setRider(null); show('Rider added — they log in with OTP'); }}>Add</button></div>}</Modal></div>;
}
