'use client';
import { useState } from 'react';
import useSWR from 'swr';
import { api, fetcher, paise, fmtDate } from '@/lib/api';
import { Modal, Field, useToast, StatusBadge } from '@/components/ui';
const TYPES = ['MILL', 'ADDON_SUPPLIER', 'PACKAGING', 'LOGISTICS', 'OTHER'];
export default function Vendors() {
  const { data, mutate } = useSWR('/admin/vendors', fetcher); const { show, Toast } = useToast();
  const [edit, setEdit] = useState<any>(null); const [sel, setSel] = useState<string | null>(null); const { data: detail, mutate: mD } = useSWR(sel ? '/admin/vendors/' + sel : null, fetcher);
  const [pay, setPay] = useState({ amountRupees: 0, ref: '' });
  const [portal, setPortal] = useState({ phone: '', name: '' });
  const save = async () => { try { if (edit.id) await api('/admin/vendors/' + edit.id, { method: 'PATCH', body: edit }); else await api('/admin/vendors', { body: edit }); setEdit(null); mutate(); show('Saved'); } catch (e: any) { show(e.message, true); } };
  return <div><Toast /><div className="flex justify-between items-center mb-4"><h1 className="text-2xl font-bold">Vendors</h1><button className="btn-primary" onClick={() => setEdit({ type: 'MILL', termsDays: 7, rating: 4 })}>+ Vendor</button></div>
    <div className="card overflow-auto"><table className="tbl"><thead><tr><th>Name</th><th>Type</th><th>District</th><th>GSTIN</th><th>Phone</th><th>Terms</th><th>Rating</th><th>Lots / POs</th><th className="text-right">Payable</th><th className="text-right">Overdue</th><th></th></tr></thead><tbody>
      {data?.map((v: any) => <tr key={v.id} className={!v.active ? 'opacity-50' : ''}><td><button className="underline font-medium" onClick={() => setSel(v.id)}>{v.name}</button></td><td><span className="badge bg-gray-100">{v.type}</span></td><td>{v.district}</td><td className="font-mono text-xs">{v.gstin}</td><td>{v.phone}</td><td>{v.termsDays} d</td><td>{'★'.repeat(v.rating || 0)}</td><td>{v._count.lots} / {v._count.pos}</td><td className="text-right">{paise(v.payablePaise)}</td><td className={'text-right ' + (v.overduePaise > 0 ? 'text-red-600 font-semibold' : '')}>{paise(v.overduePaise)}</td><td><button className="btn-secondary !py-0.5 !px-2" onClick={() => setEdit(v)}>Edit</button></td></tr>)}</tbody></table></div>
    <Modal title={edit?.id ? 'Edit vendor' : 'New vendor'} open={!!edit} onClose={() => setEdit(null)}>{edit && <div className="grid grid-cols-2 gap-2">
      <Field label="Name"><input className="input" value={edit.name || ''} onChange={(e) => setEdit({ ...edit, name: e.target.value })} /></Field><Field label="Type"><select className="input" value={edit.type} onChange={(e) => setEdit({ ...edit, type: e.target.value })}>{TYPES.map((t) => <option key={t}>{t}</option>)}</select></Field>
      <Field label="District"><input className="input" value={edit.district || ''} onChange={(e) => setEdit({ ...edit, district: e.target.value })} /></Field><Field label="GSTIN"><input className="input" value={edit.gstin || ''} onChange={(e) => setEdit({ ...edit, gstin: e.target.value })} /></Field>
      <Field label="Contact person"><input className="input" value={edit.contact || ''} onChange={(e) => setEdit({ ...edit, contact: e.target.value })} /></Field><Field label="Phone"><input className="input" value={edit.phone || ''} onChange={(e) => setEdit({ ...edit, phone: e.target.value })} /></Field>
      <Field label="Email"><input className="input" value={edit.email || ''} onChange={(e) => setEdit({ ...edit, email: e.target.value })} /></Field><Field label="Payment terms (days)"><input type="number" className="input" value={edit.termsDays} onChange={(e) => setEdit({ ...edit, termsDays: Number(e.target.value) })} /></Field>
      <Field label="Quality rating 1-5"><input type="number" min={1} max={5} className="input" value={edit.rating || ''} onChange={(e) => setEdit({ ...edit, rating: Number(e.target.value) })} /></Field><Field label="Active"><select className="input" value={edit.active === false ? '0' : '1'} onChange={(e) => setEdit({ ...edit, active: e.target.value === '1' })}><option value="1">Yes</option><option value="0">No</option></select></Field>
      <div className="col-span-2"><Field label="Address"><input className="input" value={edit.address || ''} onChange={(e) => setEdit({ ...edit, address: e.target.value })} /></Field></div><div className="col-span-2"><Field label="Notes (moisture spec, contract, etc.)"><textarea className="input" value={edit.notes || ''} onChange={(e) => setEdit({ ...edit, notes: e.target.value })} /></Field></div>
      <button className="btn-primary col-span-2" disabled={!edit.name} onClick={save}>Save</button></div>}</Modal>
    <Modal title={detail?.name || 'Vendor'} open={!!sel} onClose={() => setSel(null)}>{detail && <div className="space-y-4 text-sm">
      <div className="card"><b>Record payment</b><div className="flex gap-2 mt-2"><input className="input" type="number" placeholder="₹" value={pay.amountRupees || ''} onChange={(e) => setPay({ ...pay, amountRupees: Number(e.target.value) })} /><input className="input" placeholder="UTR / cheque" value={pay.ref} onChange={(e) => setPay({ ...pay, ref: e.target.value })} /><button className="btn-primary" onClick={async () => { await api(`/admin/vendors/${detail.id}/payments`, { body: pay }); mD(); mutate(); setPay({ amountRupees: 0, ref: '' }); show('Payment posted'); }}>Post</button></div></div>
      <div><b>Ledger</b><table className="tbl mt-1"><thead><tr><th>Date</th><th>Entry</th><th>Ref</th><th>Due</th><th className="text-right">Amount</th></tr></thead><tbody>{detail.ledger.map((l: any) => <tr key={l.id}><td>{fmtDate(l.at)}</td><td>{l.reason}</td><td className="font-mono text-xs">{l.ref}</td><td>{l.dueOn ? fmtDate(l.dueOn) : ''}</td><td className={'text-right ' + (l.deltaPaise < 0 ? 'text-green-700' : '')}>{paise(l.deltaPaise)}</td></tr>)}</tbody></table></div>
      <div><b>Purchase orders</b>{detail.pos.map((p: any) => <div key={p.id} className="flex justify-between border-b py-1"><span>PO-{p.poNo} · {p.warehouse.code} · {p.lines.map((l: any) => `${l.variety.code} ${l.receivedKg}/${l.kg}kg`).join(', ')}</span><StatusBadge s={p.status} /></div>)}</div>
      <div><b>Recent lots</b>{detail.lots.map((l: any) => <div key={l.id} className="text-xs border-b py-1">{l.lotNo} · {l.variety.name} · {l.warehouse.code} · {l.receivedKg} kg · moisture {l.moisturePct}% · {fmtDate(l.receivedAt)}</div>)}</div>
      <div className="card"><b>Vendor portal login</b><div className="text-xs text-gray-500 mb-2">Gives this mill/supplier self-service access to their own POs, deliveries and payables — nothing else.</div><div className="flex gap-2"><input className="input" placeholder="Name" value={portal.name} onChange={(e) => setPortal({ ...portal, name: e.target.value })} /><input className="input" placeholder="Phone" value={portal.phone} onChange={(e) => setPortal({ ...portal, phone: e.target.value })} /><button className="btn-primary" disabled={!portal.name || !portal.phone} onClick={async () => { await api(`/admin/vendors/${detail.id}/portal-user`, { body: portal }); setPortal({ phone: '', name: '' }); show('Portal login created'); }}>Create login</button></div></div></div>}</Modal></div>;
}
