"""multi-tenancy, auth, agent versions, licence

Revision ID: 0001_multitenancy
Revises:
Create Date: 2026-09-15

Moves an existing single-tenant Core onto the multi-tenant model:
  1. create tenancy/auth/designer/licence tables
  2. seed the platform + default tenants and their brand profiles
  3. add tenant_id to every domain table, backfill to the default tenant,
     then make it NOT NULL
  4. replace the three GLOBAL unique constraints (agents.name, trunks.name,
     numbers.e164) with composite (tenant_id, ...) ones — otherwise two tenants
     could never use the same agent name or phone number
  5. widen the audit table so entries are attributable

Written by hand rather than autogenerated: batch_alter_table on SQLite rebuilds
each table, and the constraint swap in step 4 is not something autogenerate
gets right.
"""
from __future__ import annotations

import datetime as dt

import sqlalchemy as sa
from alembic import op

revision = "0001_multitenancy"
down_revision = None
branch_labels = None
depends_on = None

PLATFORM_TENANT_ID = "ten_platform"
DEFAULT_TENANT_ID = "ten_default"

DEFAULT_COLORS = (
    '{"primary": "#6d5efc", "accent": "#22d3ee", "bg": "#07080d", '
    '"panel": "#0f111a", "text": "#f2f4f8", "muted": "#9aa2b4", '
    '"success": "#34d399", "warning": "#fbbf24", "danger": "#f87171"}'
)
DEFAULT_TYPOGRAPHY = (
    '{"font_body": "Inter Variable", "font_mono": "JetBrains Mono", "scale": 1.0}'
)
DEFAULT_RADIUS = '{"sm": "8px", "md": "12px", "lg": "18px"}'


def _has_table(name: str) -> bool:
    bind = op.get_bind()
    return sa.inspect(bind).has_table(name)


def _columns(table: str) -> set[str]:
    bind = op.get_bind()
    return {c["name"] for c in sa.inspect(bind).get_columns(table)}


def upgrade() -> None:
    now = dt.datetime.now(dt.timezone.utc)

    # -- 1. new tables ------------------------------------------------------
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("slug", sa.String(), nullable=False, unique=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="active"),
        sa.Column("is_platform", sa.Boolean(), server_default=sa.false()),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("updated_at", sa.DateTime()),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("email", sa.String(), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(), server_default=""),
        sa.Column("name", sa.String(), server_default=""),
        sa.Column("status", sa.String(), server_default="active"),
        sa.Column("must_change_password", sa.Boolean(), server_default=sa.false()),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("updated_at", sa.DateTime()),
    )

    op.create_table(
        "memberships",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("tenant_id", sa.String(), sa.ForeignKey("tenants.id"), nullable=False),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("role", sa.String(), server_default="viewer"),
        sa.Column("created_at", sa.DateTime()),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_membership"),
    )
    op.create_index("ix_memberships_tenant_id", "memberships", ["tenant_id"])
    op.create_index("ix_memberships_user_id", "memberships", ["user_id"])

    op.create_table(
        "brand_profiles",
        sa.Column("tenant_id", sa.String(), sa.ForeignKey("tenants.id"), primary_key=True),
        sa.Column("product_name", sa.String(), server_default="Lattice Net"),
        sa.Column("logo_url", sa.String(), server_default=""),
        sa.Column("logo_dark_url", sa.String(), server_default=""),
        sa.Column("favicon_url", sa.String(), server_default=""),
        sa.Column("login_art_url", sa.String(), server_default=""),
        sa.Column("colors", sa.JSON()),
        sa.Column("typography", sa.JSON()),
        sa.Column("radius", sa.JSON()),
        sa.Column("support_url", sa.String(), server_default=""),
        sa.Column("docs_url", sa.String(), server_default=""),
        sa.Column("privacy_url", sa.String(), server_default=""),
        sa.Column("terms_url", sa.String(), server_default=""),
        sa.Column("mail_from_name", sa.String(), server_default=""),
        sa.Column("mail_from_email", sa.String(), server_default=""),
        sa.Column("mail_footer", sa.Text(), server_default=""),
        sa.Column("custom_css", sa.Text(), server_default=""),
        sa.Column("updated_at", sa.DateTime()),
    )

    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("tenant_id", sa.String(), sa.ForeignKey("tenants.id"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("prefix", sa.String(), nullable=False),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("scopes", sa.JSON()),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_api_keys_tenant_id", "api_keys", ["tenant_id"])
    op.create_index("ix_api_keys_prefix", "api_keys", ["prefix"])

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("tenant_id", sa.String(), sa.ForeignKey("tenants.id"), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False, unique=True),
        sa.Column("family_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("user_agent", sa.String(), server_default=""),
        sa.Column("ip", sa.String(), server_default=""),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])
    op.create_index("ix_refresh_tokens_tenant_id", "refresh_tokens", ["tenant_id"])
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"])

    op.create_table(
        "agent_versions",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("tenant_id", sa.String(), sa.ForeignKey("tenants.id"), nullable=False),
        sa.Column("agent_id", sa.String(), sa.ForeignKey("agents.id"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1"),
        sa.Column("graph", sa.JSON()),
        sa.Column("pipeline", sa.JSON()),
        sa.Column("prompt", sa.Text(), server_default=""),
        sa.Column("tools", sa.JSON()),
        sa.Column("status", sa.String(), server_default="draft"),
        sa.Column("note", sa.String(), server_default=""),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime()),
        sa.UniqueConstraint("agent_id", "version", name="uq_agent_version"),
    )
    op.create_index("ix_agent_versions_tenant_id", "agent_versions", ["tenant_id"])
    op.create_index("ix_agent_versions_agent_id", "agent_versions", ["agent_id"])

    op.create_table(
        "licence",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("blob", sa.Text(), server_default=""),
        sa.Column("installed_at", sa.DateTime()),
    )

    # -- 2. seed tenants + brand profiles -----------------------------------
    tenants = sa.table(
        "tenants",
        sa.column("id", sa.String), sa.column("slug", sa.String),
        sa.column("name", sa.String), sa.column("status", sa.String),
        sa.column("is_platform", sa.Boolean),
        sa.column("created_at", sa.DateTime), sa.column("updated_at", sa.DateTime),
    )
    op.bulk_insert(tenants, [
        {"id": PLATFORM_TENANT_ID, "slug": "platform", "name": "Platform",
         "status": "active", "is_platform": True, "created_at": now, "updated_at": now},
        {"id": DEFAULT_TENANT_ID, "slug": "default", "name": "Default",
         "status": "active", "is_platform": False, "created_at": now, "updated_at": now},
    ])

    brands = sa.table(
        "brand_profiles",
        sa.column("tenant_id", sa.String), sa.column("product_name", sa.String),
        sa.column("colors", sa.JSON), sa.column("typography", sa.JSON),
        sa.column("radius", sa.JSON), sa.column("updated_at", sa.DateTime),
    )
    op.bulk_insert(brands, [
        {"tenant_id": tid, "product_name": "Lattice Net",
         "colors": DEFAULT_COLORS, "typography": DEFAULT_TYPOGRAPHY,
         "radius": DEFAULT_RADIUS, "updated_at": now}
        for tid in (PLATFORM_TENANT_ID, DEFAULT_TENANT_ID)
    ])

    # -- 3/4. tenant_id on domain tables + constraint swap ------------------
    #
    # The original tables declared UNIQUE(name) / UNIQUE(e164) *inline and
    # unnamed*. SQLite cannot drop an unnamed constraint, and batch_alter_table
    # copies whatever it finds in the reflected table — so a naive rebuild
    # silently carries the global constraint through and two tenants can never
    # share an agent name or phone number.
    #
    # The fix: hand batch mode an explicit naming convention plus a copy_from
    # table definition that omits the old constraint. Batch then rebuilds the
    # table from *our* definition rather than the reflected one.
    naming = {"uq": "uq_%(table_name)s_%(column_0_name)s"}

    agents_target = sa.Table(
        "agents", sa.MetaData(naming_convention=naming),
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("pipeline", sa.JSON(), nullable=False),
        sa.Column("tools", sa.JSON(), nullable=False),
        sa.Column("kb", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        # tenant_id is already present and backfilled by the time the rebuild
        # runs, so it must appear here or the INSERT..SELECT drops it.
        sa.Column("tenant_id", sa.String(), nullable=False),
    )
    with op.batch_alter_table("agents", schema=None) as b:
        b.add_column(sa.Column("tenant_id", sa.String(), nullable=True))
    op.execute(f"UPDATE agents SET tenant_id = '{DEFAULT_TENANT_ID}'")
    with op.batch_alter_table("agents", schema=None, copy_from=agents_target) as b:
        b.create_foreign_key("fk_agents_tenant", "tenants", ["tenant_id"], ["id"])
        b.create_index("ix_agents_tenant_id", ["tenant_id"])
        b.create_unique_constraint("uq_agent_name", ["tenant_id", "name"])

    with op.batch_alter_table("sessions", schema=None) as b:
        b.add_column(sa.Column("tenant_id", sa.String(), nullable=True))
    op.execute(f"UPDATE sessions SET tenant_id = '{DEFAULT_TENANT_ID}'")
    with op.batch_alter_table("sessions", schema=None) as b:
        b.alter_column("tenant_id", existing_type=sa.String(), nullable=False)
        b.create_foreign_key("fk_sessions_tenant", "tenants", ["tenant_id"], ["id"])
        b.create_index("ix_sessions_tenant_id", ["tenant_id"])

    trunks_target = sa.Table(
        "trunks", sa.MetaData(naming_convention=naming),
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("carrier", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
    )
    with op.batch_alter_table("trunks", schema=None) as b:
        b.add_column(sa.Column("tenant_id", sa.String(), nullable=True))
    op.execute(f"UPDATE trunks SET tenant_id = '{DEFAULT_TENANT_ID}'")
    with op.batch_alter_table("trunks", schema=None, copy_from=trunks_target) as b:
        b.create_foreign_key("fk_trunks_tenant", "tenants", ["tenant_id"], ["id"])
        b.create_index("ix_trunks_tenant_id", ["tenant_id"])
        b.create_unique_constraint("uq_trunk_name", ["tenant_id", "name"])

    numbers_target = sa.Table(
        "numbers", sa.MetaData(naming_convention=naming),
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("e164", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("trunk_id", sa.String(), nullable=True),
        sa.Column("tenant_id", sa.String(), nullable=False),
    )
    with op.batch_alter_table("numbers", schema=None) as b:
        b.add_column(sa.Column("tenant_id", sa.String(), nullable=True))
    op.execute(f"UPDATE numbers SET tenant_id = '{DEFAULT_TENANT_ID}'")
    with op.batch_alter_table("numbers", schema=None, copy_from=numbers_target) as b:
        b.create_foreign_key("fk_numbers_tenant", "tenants", ["tenant_id"], ["id"])
        b.create_index("ix_numbers_tenant_id", ["tenant_id"])
        b.create_unique_constraint("uq_number_e164", ["tenant_id", "e164"])

    with op.batch_alter_table("rules", schema=None) as b:
        b.add_column(sa.Column("tenant_id", sa.String(), nullable=True))
    op.execute(f"UPDATE rules SET tenant_id = '{DEFAULT_TENANT_ID}'")
    with op.batch_alter_table("rules", schema=None) as b:
        b.alter_column("tenant_id", existing_type=sa.String(), nullable=False)
        b.create_foreign_key("fk_rules_tenant", "tenants", ["tenant_id"], ["id"])
        b.create_index("ix_rules_tenant_id", ["tenant_id"])

    # -- 5. widen audit -----------------------------------------------------
    existing_audit = _columns("audit")
    with op.batch_alter_table("audit", schema=None) as b:
        b.add_column(sa.Column("tenant_id", sa.String(), nullable=True))
        if "actor_user_id" not in existing_audit:
            b.add_column(sa.Column("actor_user_id", sa.String(), nullable=True))
        if "actor_type" not in existing_audit:
            b.add_column(sa.Column("actor_type", sa.String(), server_default="system"))
        if "ip" not in existing_audit:
            b.add_column(sa.Column("ip", sa.String(), server_default=""))
        if "target" not in existing_audit:
            b.add_column(sa.Column("target", sa.String(), server_default=""))
    op.execute(f"UPDATE audit SET tenant_id = '{DEFAULT_TENANT_ID}'")
    with op.batch_alter_table("audit", schema=None) as b:
        b.alter_column("tenant_id", existing_type=sa.String(), nullable=False)
        b.create_foreign_key("fk_audit_tenant", "tenants", ["tenant_id"], ["id"])
        b.create_index("ix_audit_tenant_id", ["tenant_id"])
        b.create_index("ix_audit_ts", ["ts"])


def downgrade() -> None:
    """Reverse the migration. Auth/tenancy data is destroyed — that is the point."""
    for table, idx, fk, uq in (
        ("audit", ["ix_audit_tenant_id", "ix_audit_ts"], "fk_audit_tenant", None),
        ("rules", ["ix_rules_tenant_id"], "fk_rules_tenant", None),
        ("numbers", ["ix_numbers_tenant_id"], "fk_numbers_tenant", "uq_number_e164"),
        ("trunks", ["ix_trunks_tenant_id"], "fk_trunks_tenant", "uq_trunk_name"),
        ("sessions", ["ix_sessions_tenant_id"], "fk_sessions_tenant", None),
        ("agents", ["ix_agents_tenant_id"], "fk_agents_tenant", "uq_agent_name"),
    ):
        with op.batch_alter_table(table, schema=None) as b:
            if uq:
                b.drop_constraint(uq, type_="unique")
            b.drop_constraint(fk, type_="foreignkey")
            for i in idx:
                b.drop_index(i)
            b.drop_column("tenant_id")

    with op.batch_alter_table("audit", schema=None) as b:
        for col in ("actor_user_id", "actor_type", "ip", "target"):
            b.drop_column(col)

    for t in ("licence", "agent_versions", "refresh_tokens", "api_keys",
              "brand_profiles", "memberships", "users", "tenants"):
        if _has_table(t):
            op.drop_table(t)
