'use client';
import { useState } from 'react';
import useSWR from 'swr';
import { api, fetcher, paise, fmtDate } from '@/lib/api';
import { Modal, Field, useToast } from '@/components/ui';
export default function Warehouses() {
  const { data, mutate } = useSWR('/admin/warehouses', fetcher); const { data: zones } = useSWR('/zones', fetcher); const { data: xfers } = useSWR('/inventory/transfers', fetcher); const { show, Toast } = useToast();
  const [open, setOpen] = useState(false); const [f, setF] = useState({ code: '', name: '', address: '', pincode: '' });
  const setZone = async (whId: string, zoneId: string) => { try { await api(`/admin/warehouses/${whId}/zones`, { method: 'PATCH', body: { zoneIds: [zoneId] } }); mutate(); show('Zone mapped'); } catch (e: any) { show(e.message, true); } };
  return <div><Toast /><div className="flex justify-between items-center mb-4"><h1 className="text-2xl font-bold">Warehouses</h1><button className="btn-primary" onClick={() => setOpen(true)}>+ Warehouse</button></div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">{data?.map((w: any) => <div key={w.id} className="card"><div className="flex justify-between"><div><b>{w.code}</b> · {w.name}<div className="text-xs text-gray-500">{w.address} {w.pincode}</div></div><span className={'badge ' + (w.active ? 'bg-green-100 text-green-700' : 'bg-gray-100')}>{w.active ? 'active' : 'inactive'}</span></div>
      <div className="grid grid-cols-3 gap-2 mt-3 text-sm"><div><div className="text-xs text-gray-500">On hand</div><b>{Math.round(w.onHandKg)} kg</b></div><div><div className="text-xs text-gray-500">Lots</div><b>{w.lotCount}</b></div><div><div className="text-xs text-gray-500">Stock value</div><b>{paise(w.stockValuePaise)}</b></div></div>
      <div className="mt-3 text-sm"><div className="text-xs text-gray-500 mb-1">Serves zones</div>{w.zones.map((z: any) => <span key={z.id} className="badge bg-blue-100 text-blue-700 mr-1">{z.name}</span>)}<select className="input mt-2" defaultValue="" onChange={(e) => e.target.value && setZone(w.id, e.target.value)}><option value="">Map a zone to this warehouse…</option>{zones?.map((z: any) => <option key={z.id} value={z.id}>{z.name}</option>)}</select></div></div>)}</div>
    <h2 className="font-semibold mt-6 mb-2">Transfers</h2><div className="card"><table className="tbl"><thead><tr><th>Date</th><th>From</th><th>To</th><th>Lot</th><th>New lot</th><th>kg</th></tr></thead><tbody>{xfers?.map((t: any) => <tr key={t.id}><td>{fmtDate(t.at)}</td><td>{t.fromWarehouse.code}</td><td>{t.toWarehouse.code}</td><td className="font-mono text-xs">{t.lotNo}</td><td className="font-mono text-xs">{t.newLotNo}</td><td>{t.kg}</td></tr>)}</tbody></table>{xfers && !xfers.length && <div className="text-gray-400 text-sm">No transfers yet — use "Transfer" on a lot in Stock & lots.</div>}</div>
    <Modal title="New warehouse" open={open} onClose={() => setOpen(false)}><div className="space-y-2"><Field label="Code"><input className="input" value={f.code} onChange={(e) => setF({ ...f, code: e.target.value.toUpperCase() })} /></Field><Field label="Name"><input className="input" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /></Field><Field label="Address"><input className="input" value={f.address} onChange={(e) => setF({ ...f, address: e.target.value })} /></Field><Field label="Pincode"><input className="input" value={f.pincode} onChange={(e) => setF({ ...f, pincode: e.target.value })} /></Field><button className="btn-primary w-full" disabled={!f.code || !f.name} onClick={async () => { try { await api('/admin/warehouses', { body: f }); mutate(); setOpen(false); } catch (e: any) { show(e.message, true); } }}>Create</button></div></Modal></div>;
}
