import type { FlowStep } from "./diagrams";

export type Feature = {
  id: string;
  emoji: string;
  title: string;
  tag: string;
  tone: "emerald" | "sky" | "amber";
  summary: string;
  bullets: string[];
  flow: FlowStep[];
  edge: string; // what we do that most competitors don't
};

export const features: Feature[] = [
  {
    id: "inbox",
    emoji: "💬",
    title: "Team Inbox",
    tag: "shared · multi-agent",
    tone: "emerald",
    summary:
      "One shared inbox for every WhatsApp number, with routing, SLA timers and presence — so no message sits unanswered.",
    bullets: [
      "Unlimited agents on every plan — no per-seat inbox tax",
      "Assignment rules: round-robin, load-based, skills, teams",
      "SLA timers, snooze, priority, canned replies, private notes",
      "Collision detection and typing presence between agents",
      "WhatsApp, Facebook Messenger and Instagram Direct in one inbox",
      "Chat-history import when connecting an existing number",
    ],
    flow: [
      { icon: "📩", title: "Message arrives", detail: "Any number, any channel" },
      { icon: "🔀", title: "Auto-routed", detail: "Team, skill or round-robin rule" },
      { icon: "🧑‍💻", title: "Agent replies", detail: "Notes, tags, canned replies" },
      { icon: "✅", title: "Resolved", detail: "SLA + CSAT tracked" },
    ],
    edge: "Unlimited agents and chat-history import — most competitors charge per seat and can't import existing chats.",
  },
  {
    id: "contacts",
    emoji: "👤",
    title: "Contacts & Segments",
    tag: "audience · CRM",
    tone: "emerald",
    summary: "A clean contact database with attributes, consent tracking and behavioural segments that feed every campaign.",
    bullets: [
      "Custom attributes, tags, lifecycle stages",
      "CSV / Google Sheets import with dedupe",
      "Number-has-WhatsApp validation before you send",
      "Opt-in / opt-out with a full consent log",
      "Native CRM sync — HubSpot, Zoho, Salesforce",
    ],
    flow: [
      { icon: "📥", title: "Import", detail: "CSV, Sheets or CRM sync" },
      { icon: "🧹", title: "Dedupe & validate", detail: "E.164 + WhatsApp check" },
      { icon: "🏷️", title: "Tag & segment", detail: "Attributes, behaviour, stage" },
      { icon: "📣", title: "Ready to target", detail: "Feeds broadcasts & drips" },
    ],
    edge: "Validates a number actually has WhatsApp before you spend a message credit on it.",
  },
  {
    id: "broadcasts",
    emoji: "📣",
    title: "Broadcasts & Campaigns",
    tag: "single-send · drip · A/B",
    tone: "sky",
    summary: "Send a one-off broadcast or a multi-step drip sequence, with daily send caps and a live delivery funnel.",
    bullets: [
      "Single-message or multi-step drip sequences",
      "Scheduling, daily send-rate caps, pause-on-reply",
      "A/B split tests and retargeting by delivered/read/clicked/replied",
      "Live 5-stage funnel: sent → delivered → read → replied → failed",
      "Optional SMS fallback when a WhatsApp send fails",
    ],
    flow: [
      { icon: "🎯", title: "Pick segment", detail: "Or all opted-in contacts" },
      { icon: "📝", title: "Choose template", detail: "Single-send or drip steps" },
      { icon: "⏱️", title: "Schedule & cap", detail: "Daily limit, warm-up safe" },
      { icon: "📊", title: "Track funnel", detail: "Live delivery + reply stats" },
    ],
    edge: "Reply-triggered auto-pause and SMS fallback are built in — most SMB tools stop at \"sent\".",
  },
  {
    id: "templates",
    emoji: "📄",
    title: "Template Manager",
    tag: "whatsapp + sms",
    tone: "sky",
    summary: "Create, submit and track Meta-approved templates — marketing, utility and authentication — from one screen.",
    bullets: [
      "Guided template builder with variables and sample media",
      "Live Meta approval status and rejection reasons",
      "Category-aware cost preview before you submit",
      "Buttons, list menus, catalogue cards and WhatsApp Flows built in",
      "Versioning so a rejected edit never blocks the live template",
    ],
    flow: [
      { icon: "✏️", title: "Draft template", detail: "Variables, media, category" },
      { icon: "📤", title: "Submit to Meta", detail: "One click, tracked status" },
      { icon: "🔍", title: "Approval webhook", detail: "Approved / rejected, live" },
      { icon: "🚀", title: "Use everywhere", detail: "Broadcasts, drips, bots" },
    ],
    edge: "Shows the real Meta approval status and cost category in the same screen you build the template in.",
  },
  {
    id: "interactive",
    emoji: "🔘",
    title: "Interactive Messages",
    tag: "buttons · lists · catalogue",
    tone: "sky",
    summary:
      "Quick-reply buttons, call-to-action buttons, list menus and catalogue cards — built visually and sent as real Meta interactive messages, not plain text with a link stuck on the end.",
    bullets: [
      "Up to 3 quick-reply buttons, 2 website buttons and a call button per message",
      "List messages with sections and up to 10 selectable rows",
      "Catalogue: single product card or a full Browse Catalogue message",
      "Text, image, video or document header plus a footer line",
      "Meta's own limits enforced as you build, so nothing is rejected at send time",
      "Every tap comes back into the inbox and can trigger automations",
    ],
    flow: [
      { icon: "🎛️", title: "Build visually", detail: "Buttons, list rows or products" },
      { icon: "👀", title: "Live preview", detail: "Exactly what the customer sees" },
      { icon: "📲", title: "Sent as interactive", detail: "Real Meta message type" },
      { icon: "↩️", title: "Tap returns", detail: "Routed, tagged, automatable" },
    ],
    edge: "The preview is generated from the exact payload we send to Meta — what you see is what goes out, not a separate mock-up.",
  },
  {
    id: "flows",
    emoji: "🧾",
    title: "WhatsApp Flows",
    tag: "in-chat forms",
    tone: "sky",
    summary:
      "Native in-chat forms — booking, lead capture, surveys, sign-ups — that a customer fills in without ever leaving the chat.",
    bullets: [
      "Multi-screen builder: text, date picker, dropdown, choice, opt-in fields",
      "Live phone preview while you build",
      "One-click publish straight to Meta, with real validation errors surfaced",
      "Submissions land against the contact and conversation, not in a message blob",
      "Attach a published flow to any template or campaign",
    ],
    flow: [
      { icon: "🧱", title: "Build screens", detail: "Fields, order, CTA labels" },
      { icon: "🚀", title: "Publish to Meta", detail: "Compiled to Flow JSON" },
      { icon: "📝", title: "Customer fills in", detail: "Inside WhatsApp, no link-out" },
      { icon: "📥", title: "Answers captured", detail: "On the contact + conversation" },
    ],
    edge: "Answers are stored as structured, queryable responses — most tools drop a flow submission into the chat as raw text.",
  },
  {
    id: "bots",
    emoji: "🤖",
    title: "Bots & AI Agent",
    tag: "no-code · RAG",
    tone: "amber",
    summary: "A visual, no-code bot builder plus an AI agent that answers from your own knowledge base and can hand off to a human.",
    bullets: [
      "Drag-and-drop flow builder — triggers, conditions, HTTP calls, delays",
      "AI agent with RAG over your docs, FAQs and catalog",
      "AI tools: order lookup, booking, CRM write, human handoff",
      "Agent-assist: draft replies, summarise threads, translate",
      "Sentiment detection and auto-tagging on every conversation",
    ],
    flow: [
      { icon: "⚡", title: "Trigger", detail: "Keyword, new chat, ad click" },
      { icon: "🌳", title: "Bot graph runs", detail: "Conditions, HTTP, waits" },
      { icon: "🧠", title: "AI node (optional)", detail: "RAG on your knowledge base" },
      { icon: "🙋", title: "Handoff or resolve", detail: "To a team, with summary" },
    ],
    edge: "The AI agent and the no-code bot builder are the same product — not a bolted-on separate \"AI add-on\" like most rivals sell.",
  },
  {
    id: "automations",
    emoji: "🔀",
    title: "Automation Rules",
    tag: "triggers · actions",
    tone: "amber",
    summary: "Lightweight trigger → condition → action rules for the things that shouldn't need a full bot flow.",
    bullets: [
      "Trigger on tag added, segment entered, order placed, no-agent-online",
      "Conditions on contact attributes, time of day, channel",
      "Actions: assign, tag, notify, start a drip, call a webhook",
      "Runs alongside the bot engine without conflicting",
    ],
    flow: [
      { icon: "🔔", title: "Event happens", detail: "Tag, order, schedule, reply" },
      { icon: "🧩", title: "Condition matches", detail: "Attribute, time, channel" },
      { icon: "🎬", title: "Action fires", detail: "Assign, tag, notify, webhook" },
    ],
    edge: "Rules and the full bot builder share one automation engine, so they never fight over the same conversation.",
  },
  {
    id: "ads-social",
    emoji: "📢",
    title: "Ads & Social Manager",
    tag: "7 ad platforms · 5 organic",
    tone: "amber",
    summary: "Run Click-to-WhatsApp ads and manage WhatsApp Channels, groups, communities and status posts — all from one manager.",
    bullets: [
      "Click-to-WhatsApp ads with referral attribution and ROAS",
      "WhatsApp Channels (newsletter) publisher with scheduling",
      "Groups & communities manager with join-triggered bots",
      "Status / story scheduler and group broadcasts",
      "Meta Ads spend pulled nightly for real cost-per-conversation",
    ],
    flow: [
      { icon: "🖼️", title: "Ad or post", detail: "CTWA ad, channel post, status" },
      { icon: "👋", title: "Referral lands", detail: "72h free-entry window opens" },
      { icon: "💬", title: "Conversation opens", detail: "Tagged to the ad/post" },
      { icon: "📈", title: "ROAS reported", detail: "Spend vs. replies & orders" },
    ],
    edge: "Groups, Channels/newsletter publishing and a status scheduler — features the official API doesn't expose, and almost nobody else offers.",
  },
  {
    id: "channels",
    emoji: "🔌",
    title: "Channels",
    tag: "official + quick connect",
    tone: "sky",
    summary: "Connect a number the official way in minutes via Embedded Signup, or go live instantly with Quick Connect.",
    bullets: [
      "Official Meta Cloud API via Embedded Signup — verified, green-tick eligible",
      "Quick Connect (QR) — live in under 2 minutes, no Meta paperwork",
      "Multiple numbers per organisation",
      "Per-number quality-rating and safety-score trending",
      "One-click migration path from Quick Connect to Official",
    ],
    flow: [
      { icon: "➕", title: "Connect number", detail: "Embedded Signup or QR" },
      { icon: "🩺", title: "Health tracked", detail: "Quality rating, safety score" },
      { icon: "📶", title: "Live in inbox", detail: "Shared across all agents" },
      { icon: "🔁", title: "Upgrade anytime", detail: "Quick Connect → Official" },
    ],
    edge: "The only platform offering both an official channel and a QR-based Quick Connect tier with a clear ban-risk disclosure and upgrade path.",
  },
  {
    id: "analytics",
    emoji: "📊",
    title: "Analytics",
    tag: "reporting · ROI",
    tone: "emerald",
    summary: "Delivery funnels, campaign ROI, agent performance and per-number quality trends — without opening a spreadsheet.",
    bullets: [
      "Delivery / read / click / reply funnel per campaign",
      "Campaign ROI and live Meta cost mirror",
      "Agent SLA, workload and resolution leaderboard",
      "Per-number quality-rating and safety-score trends",
      "Scheduled PDF/CSV reports to your inbox",
    ],
    flow: [
      { icon: "📡", title: "Events stream in", detail: "Messages, statuses, campaigns" },
      { icon: "⚙️", title: "Rolled up", detail: "By campaign, agent, number" },
      { icon: "📋", title: "Dashboard", detail: "Funnels, ROI, leaderboards" },
      { icon: "📧", title: "Scheduled report", detail: "PDF / CSV, on autopilot" },
    ],
    edge: "Per-number safety-score trending is unique — most platforms only show you delivery stats, not whether a number is at ban risk.",
  },
  {
    id: "commerce",
    emoji: "🛒",
    title: "Commerce & Payments",
    tag: "catalog · orders · pay",
    tone: "sky",
    summary: "Sync your catalog, take orders inside WhatsApp, and get paid with Razorpay, PayU or WhatsApp Pay.",
    bullets: [
      "Catalog sync with Meta Commerce Manager",
      "Cart and order objects, tracked end to end",
      "Payment links and WhatsApp Pay (India)",
      "Shopify / WooCommerce: abandoned cart, COD confirmation, order updates",
    ],
    flow: [
      { icon: "🗂️", title: "Catalog synced", detail: "Meta Commerce Manager" },
      { icon: "🛍️", title: "Customer orders", detail: "Cart inside WhatsApp" },
      { icon: "💳", title: "Payment link", detail: "Razorpay / PayU / WA Pay" },
      { icon: "📦", title: "Order updates", detail: "Utility templates, Shopify sync" },
    ],
    edge: "0% markup on messages means checkout confirmations don't quietly eat your margin.",
  },
  {
    id: "partner",
    emoji: "🏢",
    title: "Partner & White-label",
    tag: "agency · reseller",
    tone: "amber",
    summary: "Run a full agency business on top of the platform — your brand, your domain, your clients, your margin.",
    bullets: [
      "Partner console with sub-organisations and client logins",
      "Custom domain and full branding (logo, colours, favicon)",
      "Partner API to create orgs and channels programmatically",
      "Wholesale billing and a revenue-share ledger",
      "Client-owned WABA — no lock-in for your customers",
    ],
    flow: [
      { icon: "🏷️", title: "Brand it", detail: "Domain, logo, colours" },
      { icon: "🏗️", title: "Create client orgs", detail: "Console or Partner API" },
      { icon: "👥", title: "Client logins", detail: "They see only their org" },
      { icon: "💰", title: "Wholesale billing", detail: "Rev-share ledger, monthly" },
    ],
    edge: "Custom domain + full branding + wholesale billing + rev-share + client logins in one product — no other platform in this space bundles all five.",
  },
  {
    id: "developer",
    emoji: "🧑‍💻",
    title: "Developer Platform",
    tag: "rest api · webhooks",
    tone: "amber",
    summary:
      "A documented REST API and signed outbound webhooks, so the platform fits into whatever you have already built.",
    bullets: [
      "Scoped API keys — only the hash is stored, the key is shown once",
      "Template Send Message API: fire an approved template, buttons intact, to any number",
      "Send free-form and interactive messages, read and write contacts and conversations",
      "Outbound webhooks for messages, statuses, assignments, campaigns and flow responses",
      "HMAC-SHA256 signed deliveries with timestamps, 5 retries and a delivery log",
    ],
    flow: [
      { icon: "🔑", title: "Create a key", detail: "Scoped, revocable, hashed" },
      { icon: "📮", title: "Call the API", detail: "Send templates or messages" },
      { icon: "🪝", title: "Subscribe events", detail: "Pick exactly what you need" },
      { icon: "✅", title: "Verify signature", detail: "Replay-safe HMAC + timestamp" },
    ],
    edge: "Signed, retried webhooks with a visible delivery log — not a single fire-and-forget callback URL you can never debug.",
  },
  {
    id: "settings",
    emoji: "⚙️",
    title: "Security & Enterprise",
    tag: "rbac · audit · billing",
    tone: "emerald",
    summary: "The controls a real organisation needs: roles, audit trail, two-factor auth and GST-ready billing.",
    bullets: [
      "Role-based access control and an append-only audit log",
      "Two-factor authentication for every user",
      "GST invoices, INR (Razorpay) and USD (Stripe) billing",
      "Prepaid wallet metered per 24-hour conversation, exactly as Meta bills",
      "SSO/SAML and data-residency controls on the roadmap",
    ],
    flow: [
      { icon: "🔑", title: "Invite & role", detail: "Owner, admin, agent, viewer" },
      { icon: "🛡️", title: "Every action logged", detail: "Who, what, diff, IP" },
      { icon: "🔒", title: "2FA enforced", detail: "Per user or org-wide" },
      { icon: "🧾", title: "GST invoice", detail: "Auto-generated, monthly" },
    ],
    edge: "GST-ready invoicing and an audit log ship on day one — usually an \"Enterprise plan only\" feature elsewhere.",
  },
];
