'use client';
import { useState } from 'react';
import useSWR from 'swr';
import { api, fetcher } from '@/lib/api';
import { Modal, Field, useToast } from '@/components/ui';
export default function Zones() {
  const { data, mutate } = useSWR('/zones', fetcher); const { data: whs } = useSWR('/admin/warehouses', fetcher); const { show, Toast } = useToast();
  const [edit, setEdit] = useState<any>(null); const [slotFor, setSlotFor] = useState<any>(null); const [slot, setSlot] = useState({ label: '07:00-10:00', startHour: 7, endHour: 10, capacity: 60 });
  const save = async () => { try { const body = { ...edit, pincodes: String(edit.pincodes).split(/[,\s]+/).filter(Boolean) }; if (edit.id) await api('/admin/zones/' + edit.id, { method: 'PATCH', body }); else await api('/admin/zones', { body }); setEdit(null); mutate(); show('Saved'); } catch (e: any) { show(e.message, true); } };
  return <div><Toast /><div className="flex justify-between items-center mb-4"><h1 className="text-2xl font-bold">Zones & slots</h1><button className="btn-primary" onClick={() => setEdit({ name: '', pincodes: '', warehouseId: whs?.[0]?.id })}>+ Zone</button></div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">{data?.map((z: any) => <div key={z.id} className="card"><div className="flex justify-between"><div><b>{z.name}</b> <span className={'badge ' + (z.active ? 'bg-green-100 text-green-700' : 'bg-gray-100')}>{z.active ? 'active' : 'inactive'}</span><div className="text-xs text-gray-500 mt-1">Pincodes: {z.pincodes.join(', ')}</div><div className="text-xs text-gray-500">Warehouse: {whs?.find((w: any) => w.id === z.warehouseId)?.code || '—'}</div></div><button className="btn-secondary !py-0.5 !px-2" onClick={() => setEdit({ ...z, pincodes: z.pincodes.join(', ') })}>Edit</button></div>
      <table className="tbl mt-2"><thead><tr><th>Slot</th><th>Hours</th><th>Capacity</th><th></th></tr></thead><tbody>{z.slots.map((s: any) => <tr key={s.id}><td>{s.label}</td><td>{s.startHour}–{s.endHour}</td><td><input type="number" className="input !w-20 !py-0.5" defaultValue={s.capacity} onBlur={async (e) => { await api('/admin/slots/' + s.id, { method: 'PATCH', body: { capacity: Number(e.target.value) } }); show('Capacity updated'); }} /></td><td><button className="text-red-600 text-xs" onClick={async () => { try { await api('/admin/slots/' + s.id, { method: 'DELETE' }); mutate(); } catch (e: any) { show(e.message, true); } }}>remove</button></td></tr>)}</tbody></table>
      <button className="btn-secondary mt-2 !py-1" onClick={() => setSlotFor(z)}>+ Slot</button></div>)}</div>
    <Modal title={edit?.id ? 'Edit zone' : 'New zone'} open={!!edit} onClose={() => setEdit(null)}>{edit && <div className="space-y-2"><Field label="Name"><input className="input" value={edit.name} onChange={(e) => setEdit({ ...edit, name: e.target.value })} /></Field><Field label="Pincodes (comma separated)"><textarea className="input" value={edit.pincodes} onChange={(e) => setEdit({ ...edit, pincodes: e.target.value })} /></Field><Field label="Warehouse"><select className="input" value={edit.warehouseId || ''} onChange={(e) => setEdit({ ...edit, warehouseId: e.target.value })}>{whs?.map((w: any) => <option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></Field>{edit.id && <Field label="Active"><select className="input" value={edit.active ? '1' : '0'} onChange={(e) => setEdit({ ...edit, active: e.target.value === '1' })}><option value="1">Yes</option><option value="0">No</option></select></Field>}<button className="btn-primary w-full" disabled={!edit.name} onClick={save}>Save</button></div>}</Modal>
    <Modal title={slotFor ? `New slot · ${slotFor.name}` : ''} open={!!slotFor} onClose={() => setSlotFor(null)}><div className="grid grid-cols-2 gap-2"><Field label="Label"><input className="input" value={slot.label} onChange={(e) => setSlot({ ...slot, label: e.target.value })} /></Field><Field label="Capacity"><input type="number" className="input" value={slot.capacity} onChange={(e) => setSlot({ ...slot, capacity: Number(e.target.value) })} /></Field><Field label="Start hour"><input type="number" className="input" value={slot.startHour} onChange={(e) => setSlot({ ...slot, startHour: Number(e.target.value) })} /></Field><Field label="End hour"><input type="number" className="input" value={slot.endHour} onChange={(e) => setSlot({ ...slot, endHour: Number(e.target.value) })} /></Field><button className="btn-primary col-span-2" onClick={async () => { await api(`/admin/zones/${slotFor.id}/slots`, { body: slot }); setSlotFor(null); mutate(); }}>Add</button></div></Modal></div>;
}
