'use client';
import { useState } from 'react';
import useSWR from 'swr';
import { api, fetcher, ymd, fmtDate, fmtDT } from '@/lib/api';
import { StatusBadge, useToast } from '@/components/ui';
export default function Dispatch() {
  const [date, setDate] = useState(ymd(new Date(Date.now() + 86400000))); const [vt, setVt] = useState('THREE_WHEELER'); const { show, Toast } = useToast();
  const { data: routes, mutate } = useSWR('/admin/dispatch/routes?date=' + date, fetcher, { refreshInterval: 15000 }); const { data: riders } = useSWR('/admin/riders', fetcher); const { data: live } = useSWR('/admin/dispatch/live', fetcher, { refreshInterval: 15000 }); const { data: pending } = useSWR('/admin/orders?date=' + date, fetcher);
  const unbatched = pending?.filter((o: any) => ['CONFIRMED'].includes(o.status) && !o.stop) || [];
  const batch = async () => { try { const r = await api('/admin/dispatch/batch', { body: { date, vehicleType: vt } }); show(`${r.ordersBatched} orders → ${r.routesCreated} routes`); mutate(); } catch (e: any) { show(e.message, true); } };
  const assign = async (id: string, riderId: string) => { try { await api(`/admin/dispatch/routes/${id}/assign`, { body: { riderId } }); mutate(); show('Assigned & published to rider app'); } catch (e: any) { show(e.message, true); } };
  return <div><Toast /><div className="flex justify-between items-center mb-4"><h1 className="text-2xl font-bold">Dispatch board</h1><div className="flex gap-2 items-center"><input type="date" className="input" value={date} onChange={(e) => setDate(e.target.value)} /><select className="input" value={vt} onChange={(e) => setVt(e.target.value)}><option value="TWO_WHEELER">2-wheeler (30 kg)</option><option value="THREE_WHEELER">3-wheeler (150 kg)</option><option value="TEMPO">Tempo (600 kg)</option></select><button className="btn-primary" onClick={batch} disabled={!unbatched.length}>Auto-batch {unbatched.length} confirmed orders</button></div></div>
    <p className="text-sm text-gray-600 mb-4">Batching groups confirmed orders by zone → slot → apartment complex, fills vehicles by kg. 25 kg+ orders never go on 2-wheelers. Assigning a rider publishes the manifest to the rider app; the rider's "Start route" sends delivery OTPs to customers.</p>
    {live?.some((r: any) => r.route) && <div className="card mb-4"><b>Live riders</b><div className="grid grid-cols-1 md:grid-cols-3 gap-2 mt-2 text-sm">{live.filter((r: any) => r.route).map((r: any) => <div key={r.id} className="border rounded-lg p-2"><b>{r.name}</b> · {r.route.zone}<div className="text-xs text-gray-600">{r.route.delivered}/{r.route.stops} delivered{r.loc && <> · last seen {fmtDT(r.loc.at)} <a className="underline" target="_blank" href={`https://maps.google.com/?q=${r.loc.lat},${r.loc.lng}`}>map</a></>}</div></div>)}</div></div>}
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">{routes?.map((r: any) => <div key={r.id} className="card"><div className="flex justify-between items-start"><div><b>{r.zone.name}</b> · {fmtDate(r.date)}<div className="text-xs text-gray-500">{r.vehicleType.replace('_', ' ')} · {r.loadKg}/{r.capacityKg} kg · {r.stops.length} stops</div></div><StatusBadge s={r.status} /></div>
      <div className="mt-2 flex gap-2 items-center text-sm">{r.status === 'DRAFT' && <button className="btn-secondary !py-0.5 !px-2" onClick={async () => { await api(`/admin/dispatch/routes/${r.id}/optimise`, { method: 'POST' }); mutate(); }}>Re-order stops</button>}Rider: {r.rider ? <b>{r.rider.name}</b> : <select className="input max-w-[200px]" defaultValue="" onChange={(e) => e.target.value && assign(r.id, e.target.value)}><option value="">Assign rider…</option>{riders?.map((x: any) => <option key={x.id} value={x.id}>{x.name} ({x.phone})</option>)}</select>}</div>
      <ol className="mt-2 text-xs space-y-1">{r.stops.map((s: any) => <li key={s.id} className="flex justify-between border-b border-gray-100 py-1"><span>{s.seq}. #{s.order.orderNo} · {s.order.address.complex || s.order.address.line1} · {s.order.totalKg} kg · {s.order.user.name}{s.order.payment?.method === 'COD' ? ' · COD' : ''}</span><StatusBadge s={s.status} /></li>)}</ol></div>)}
      {routes && !routes.length && <div className="text-gray-400">No routes for this date yet.</div>}</div></div>;
}
