'use client';
import { useState } from 'react';
import useSWR from 'swr';
import { api, fetcher, paise, fmtDate, fmtDT, API, getToken, getUser } from '@/lib/api';
import { StatusBadge, useToast, Field, Modal, Stat, Empty } from '@/components/ui';
import { CostComposition, CostByVehicle } from '@/components/cost-bars';

const TABS = ['Overview', 'Vehicles', 'Vendors', 'Expenses', 'Checks'] as const;
const thisMonth = () => new Date().toISOString().slice(0, 7);
const VT = ['TWO_WHEELER', 'THREE_WHEELER', 'TEMPO']; const BASIS = ['PER_MONTH', 'PER_DAY', 'PER_TRIP', 'PER_KM']; const LOGT = ['FUEL', 'MAINTENANCE', 'REPAIR', 'TOLL', 'FINE', 'OTHER'];
const DOCS: [string, string][] = [['insuranceExpiry', 'Insurance'], ['pucExpiry', 'PUC'], ['fitnessExpiry', 'Fitness'], ['permitExpiry', 'Permit']];

export default function Fleet() {
  const [tab, setTab] = useState<(typeof TABS)[number]>('Overview');
  return <div><div className="flex justify-between items-center mb-3 flex-wrap gap-2"><h1 className="text-2xl font-bold">Fleet</h1><div className="flex gap-1">{TABS.map((t) => <button key={t} className={(tab === t ? 'btn-primary' : 'btn-secondary') + ' !py-1'} onClick={() => setTab(t)}>{t}</button>)}</div></div>
    {tab === 'Overview' && <Overview />}{tab === 'Vehicles' && <Vehicles />}{tab === 'Vendors' && <Vendors />}{tab === 'Expenses' && <Expenses />}{tab === 'Checks' && <Checks />}</div>;
}

function Overview() {
  const [month, setMonth] = useState(thisMonth()); const { data: d } = useSWR(`/admin/fleet/dashboard?month=${month}`, fetcher, { refreshInterval: 60000 });
  if (!d) return <div className="text-gray-400">Loading…</div>; const c = d.counts, m = d.month_cost;
  return <div><div className="flex gap-2 items-center mb-3"><input type="month" className="input" value={month} onChange={(e) => setMonth(e.target.value)} /><a className="btn-secondary !py-1" target="_blank" href={`${API}/v1/admin/fleet/export?dataset=costs&month=${month}&format=xlsx&t=${getToken()}`}>Cost sheet XLSX</a></div>
    <div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-3 mb-4"><Stat label="Vehicles" value={c.vehicles} sub={`${c.hired} hired`} /><Stat label="Active" value={c.active} sub={`${c.unassigned} unassigned`} warn={c.unassigned > 0} /><Stat label="In maintenance" value={c.maintenance} warn={c.maintenance > 0} /><Stat label="Doc / service alerts" value={c.docAlerts} warn={c.docAlerts > 0} /><Stat label="Failed checks (7d)" value={c.failedChecks7d} warn={c.failedChecks7d > 0} /><Stat label="Owed to vendors" value={paise(c.vendorsOwedPaise)} warn={c.vendorsOwedPaise > 0} /><Stat label={`Fleet cost ${month}`} value={paise(m.totalPaise)} sub={`fuel ${paise(m.fuelPaise)} · hire ${paise(m.hirePaise)}`} /><Stat label="Cost per drop" value={m.costPerDropPaise != null ? paise(m.costPerDropPaise) : '—'} sub={`${m.drops} drops`} /></div>
    {d.alerts.length > 0 && <div className="card mb-4"><b>Alerts</b><div className="mt-1 flex flex-wrap gap-1">{d.alerts.map((a: any, i: number) => <span key={i} className={'badge ' + (a.severity === 'due' ? 'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800')}>{a.regNo} · {a.kind} {a.detail}</span>)}</div></div>}
    <div className="grid gap-3 lg:grid-cols-2 mb-4">
      <div className="card-modern">
        <div className="font-semibold mb-1">Where the money went · {month}</div>
        <div className="text-xs text-gray-500 mb-2">Total {paise(m.totalPaise)}{m.costPerDropPaise ? ` · ${paise(m.costPerDropPaise)} per drop` : ''}</div>
        <CostComposition parts={m} total={m.totalPaise} />
      </div>
      <div className="card-modern">
        <div className="font-semibold mb-2">Cost by vehicle</div>
        <CostByVehicle rows={d.costs.map((v: any) => ({ id: v.vehicleId, label: v.regNo, sub: [v.vendor, v.type?.replace('_', ' ').toLowerCase()].filter(Boolean).join(' · '), parts: v, total: v.totalPaise }))} />
      </div>
    </div>
    <div className="card overflow-auto"><b>Cost per vehicle · {month}</b><table className="tbl text-sm mt-2"><thead><tr><th>Vehicle</th><th>Vendor</th><th>Hire</th><th>Fuel</th><th>Maint.</th><th>Other</th><th>Total</th><th>Trips</th><th>Drops</th><th>km</th><th>₹/drop</th><th>₹/km</th><th>km/l</th></tr></thead><tbody>
      {d.costs.map((v: any) => <tr key={v.vehicleId}><td><b>{v.regNo}</b><br /><small>{v.type.replace('_', ' ').toLowerCase()} · {v.ownership.toLowerCase()} · <StatusBadge s={v.status} /></small></td><td className="text-xs">{v.vendor || '—'}</td><td>{paise(v.hirePaise)}{v.hireEstimated && <small className="text-gray-400"> est.</small>}</td><td>{paise(v.fuelPaise)}</td><td>{paise(v.maintenancePaise)}</td><td>{paise(v.otherPaise)}</td><td className="font-semibold">{paise(v.totalPaise)}</td><td>{v.trips}</td><td>{v.drops}</td><td>{v.km}</td><td>{v.costPerDropPaise != null ? paise(v.costPerDropPaise) : '—'}</td><td>{v.costPerKmPaise != null ? paise(v.costPerKmPaise) : '—'}</td><td>{v.kmPerLitre ?? '—'}</td></tr>)}</tbody></table>{!d.costs.length && <Empty text="Add vehicles to see costs" />}</div></div>;
}

function Vehicles() {
  const { show, Toast } = useToast(); const { data, mutate } = useSWR('/admin/fleet/vehicles', fetcher); const { data: vendors } = useSWR('/admin/fleet/vendors', fetcher); const { data: riders } = useSWR('/admin/riders', fetcher);
  const [edit, setEdit] = useState<any>(null); const [view, setView] = useState<string | null>(null); const [log, setLog] = useState<any>(null);
  const blank = { regNo: '', type: 'THREE_WHEELER', ownership: 'OWNED', vendorId: '', make: '', model: '', capacityKg: 150, fuelType: 'PETROL', hireRate: 0, hireBasis: 'PER_MONTH', assignedRiderId: '', status: 'ACTIVE', odometerKm: 0, insuranceExpiry: '', pucExpiry: '', fitnessExpiry: '', permitExpiry: '', notes: '' };
  const save = async () => { try { const { id, hireRate, ...rest } = edit; const body: any = { ...rest, hireRatePaise: Math.round(Number(hireRate || 0) * 100), vendorId: rest.vendorId || null, assignedRiderId: rest.assignedRiderId || null }; for (const [k] of DOCS) body[k] = rest[k] || null; await api(id ? `/admin/fleet/vehicles/${id}` : '/admin/fleet/vehicles', { method: id ? 'PATCH' : 'POST', body }); show('Saved'); setEdit(null); mutate(); } catch (e: any) { show(e.message, true); } };
  const addLog = async () => { try { await api(`/admin/fleet/vehicles/${log.vehicleId}/logs`, { body: { ...log, amountPaise: Math.round(Number(log.amount || 0) * 100), odometerKm: log.odometerKm || undefined, litres: log.litres || undefined, nextDueKm: log.nextDueKm || undefined, nextDueOn: log.nextDueOn || undefined } }); show('Logged'); setLog(null); mutate(); } catch (e: any) { show(e.message, true); } };
  return <div><Toast /><div className="flex justify-end mb-3"><button className="btn-primary" onClick={() => setEdit({ ...blank })}>+ Vehicle</button></div>
    <div className="card overflow-auto"><table className="tbl"><thead><tr><th>Reg no</th><th>Type</th><th>Owner</th><th>Rider</th><th>Odometer</th><th>Docs</th><th>Status</th><th></th></tr></thead><tbody>
      {data?.map((v: any) => <tr key={v.id} className={v.active ? '' : 'opacity-50'}><td><button className="underline font-semibold" onClick={() => setView(v.id)}>{v.regNo}</button><br /><small className="text-gray-500">{[v.make, v.model].filter(Boolean).join(' ')} · {v.fuelType}</small></td><td className="text-xs">{v.type.replace('_', ' ').toLowerCase()}<br />{v.capacityKg} kg</td><td className="text-xs">{v.ownership === 'HIRED' ? <>{v.vendor?.name}<br />{paise(v.hireRatePaise)} {v.hireBasis.replace('PER_', '/').toLowerCase()}</> : 'owned'}</td><td className="text-xs">{v.rider ? <>{v.rider.name}<br />{v.rider.phone}</> : <span className="text-amber-700">unassigned</span>}</td><td>{v.odometerKm} km</td><td className="text-xs">{v.docAlerts.length ? v.docAlerts.map((a: any) => <span key={a.doc} className={'badge mr-1 ' + (a.expired ? 'bg-red-100 text-red-800' : 'bg-amber-100')}>{a.doc} {fmtDate(a.expiresOn)}</span>) : <span className="text-leaf-700">ok</span>}</td><td><StatusBadge s={v.status} /></td>
        <td className="whitespace-nowrap"><button className="btn-secondary !py-0.5 !px-2 text-xs mr-1" onClick={() => setEdit({ id: v.id, regNo: v.regNo, type: v.type, ownership: v.ownership, vendorId: v.vendorId || '', make: v.make || '', model: v.model || '', capacityKg: v.capacityKg, fuelType: v.fuelType, hireRate: v.hireRatePaise / 100, hireBasis: v.hireBasis, assignedRiderId: v.assignedRiderId || '', status: v.status, odometerKm: v.odometerKm, insuranceExpiry: v.insuranceExpiry?.slice(0, 10) || '', pucExpiry: v.pucExpiry?.slice(0, 10) || '', fitnessExpiry: v.fitnessExpiry?.slice(0, 10) || '', permitExpiry: v.permitExpiry?.slice(0, 10) || '', notes: v.notes || '', active: v.active })}>Edit</button><button className="btn-secondary !py-0.5 !px-2 text-xs" onClick={() => setLog({ vehicleId: v.id, regNo: v.regNo, type: 'FUEL', amount: '', date: new Date().toISOString().slice(0, 10), odometerKm: '', litres: '', vendorName: '', description: '', nextDueKm: '', nextDueOn: '' })}>+ Expense</button></td></tr>)}</tbody></table>{data && !data.length && <Empty text="No vehicles yet" />}</div>
    <Modal title={edit?.id ? `Edit ${edit.regNo}` : 'New vehicle'} open={!!edit} onClose={() => setEdit(null)}>{edit && <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
      <Field label="Reg no"><input className="input" value={edit.regNo} onChange={(e) => setEdit({ ...edit, regNo: e.target.value })} /></Field><Field label="Type"><select className="input" value={edit.type} onChange={(e) => setEdit({ ...edit, type: e.target.value })}>{VT.map((t) => <option key={t}>{t}</option>)}</select></Field><Field label="Capacity kg"><input type="number" className="input" value={edit.capacityKg} onChange={(e) => setEdit({ ...edit, capacityKg: e.target.value })} /></Field>
      <Field label="Make"><input className="input" value={edit.make} onChange={(e) => setEdit({ ...edit, make: e.target.value })} /></Field><Field label="Model"><input className="input" value={edit.model} onChange={(e) => setEdit({ ...edit, model: e.target.value })} /></Field><Field label="Fuel"><select className="input" value={edit.fuelType} onChange={(e) => setEdit({ ...edit, fuelType: e.target.value })}>{['PETROL', 'DIESEL', 'CNG', 'EV'].map((t) => <option key={t}>{t}</option>)}</select></Field>
      <Field label="Ownership"><select className="input" value={edit.ownership} onChange={(e) => setEdit({ ...edit, ownership: e.target.value })}><option>OWNED</option><option>HIRED</option></select></Field>
      {edit.ownership === 'HIRED' && <><Field label="Vendor"><select className="input" value={edit.vendorId} onChange={(e) => setEdit({ ...edit, vendorId: e.target.value })}><option value="">—</option>{vendors?.map((v: any) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></Field><Field label="Hire rate ₹"><div className="flex gap-1"><input type="number" className="input" value={edit.hireRate} onChange={(e) => setEdit({ ...edit, hireRate: e.target.value })} /><select className="input" value={edit.hireBasis} onChange={(e) => setEdit({ ...edit, hireBasis: e.target.value })}>{BASIS.map((b) => <option key={b} value={b}>{b.replace('PER_', '/').toLowerCase()}</option>)}</select></div></Field></>}
      <Field label="Assigned rider"><select className="input" value={edit.assignedRiderId} onChange={(e) => setEdit({ ...edit, assignedRiderId: e.target.value })}><option value="">—</option>{riders?.map((r: any) => <option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="Status"><select className="input" value={edit.status} onChange={(e) => setEdit({ ...edit, status: e.target.value })}>{['ACTIVE', 'MAINTENANCE', 'INACTIVE'].map((s) => <option key={s}>{s}</option>)}</select></Field><Field label="Odometer km"><input type="number" className="input" value={edit.odometerKm} onChange={(e) => setEdit({ ...edit, odometerKm: e.target.value })} /></Field>
      {DOCS.map(([k, l]) => <Field key={k} label={`${l} expiry`}><input type="date" className="input" value={edit[k]} onChange={(e) => setEdit({ ...edit, [k]: e.target.value })} /></Field>)}
      <div className="col-span-full"><Field label="Notes"><input className="input" value={edit.notes} onChange={(e) => setEdit({ ...edit, notes: e.target.value })} /></Field></div>
      <div className="col-span-full flex justify-end gap-2"><button className="btn-secondary" onClick={() => setEdit(null)}>Cancel</button><button className="btn-primary" onClick={save}>Save</button></div></div>}</Modal>
    <Modal title={log ? `Expense · ${log.regNo}` : ''} open={!!log} onClose={() => setLog(null)}>{log && <div className="grid grid-cols-2 gap-2"><Field label="Type"><select className="input" value={log.type} onChange={(e) => setLog({ ...log, type: e.target.value })}>{LOGT.map((t) => <option key={t}>{t}</option>)}</select></Field><Field label="Amount ₹"><input type="number" className="input" value={log.amount} onChange={(e) => setLog({ ...log, amount: e.target.value })} /></Field><Field label="Date"><input type="date" className="input" value={log.date} onChange={(e) => setLog({ ...log, date: e.target.value })} /></Field><Field label="Odometer km"><input type="number" className="input" value={log.odometerKm} onChange={(e) => setLog({ ...log, odometerKm: e.target.value })} /></Field>
      {log.type === 'FUEL' && <Field label="Litres"><input type="number" step="0.1" className="input" value={log.litres} onChange={(e) => setLog({ ...log, litres: e.target.value })} /></Field>}<Field label="Vendor / garage"><input className="input" value={log.vendorName} onChange={(e) => setLog({ ...log, vendorName: e.target.value })} /></Field>
      {['MAINTENANCE', 'REPAIR'].includes(log.type) && <><Field label="Next service km"><input type="number" className="input" value={log.nextDueKm} onChange={(e) => setLog({ ...log, nextDueKm: e.target.value })} /></Field><Field label="Next service date"><input type="date" className="input" value={log.nextDueOn} onChange={(e) => setLog({ ...log, nextDueOn: e.target.value })} /></Field></>}
      <div className="col-span-2"><Field label="Description"><input className="input" value={log.description} onChange={(e) => setLog({ ...log, description: e.target.value })} /></Field></div><div className="col-span-2 flex justify-end gap-2"><button className="btn-secondary" onClick={() => setLog(null)}>Cancel</button><button className="btn-primary" onClick={addLog}>Save</button></div></div>}</Modal>
    {view && <VehicleDetail id={view} onClose={() => setView(null)} />}</div>;
}

function VehicleDetail({ id, onClose }: { id: string; onClose: () => void }) {
  const { data: v, mutate } = useSWR(`/admin/fleet/vehicles/${id}`, fetcher); const me = getUser();
  return <Modal title={v ? `${v.regNo} · ${v.status}` : 'Vehicle'} open onClose={onClose}>{!v ? <div className="text-gray-400">Loading…</div> : <div className="text-sm space-y-3">
    <div className="grid grid-cols-2 md:grid-cols-4 gap-2"><Stat label="Odometer" value={`${v.odometerKm} km`} /><Stat label="This month" value={paise(v.thisMonth?.totalPaise || 0)} sub={v.thisMonth?.costPerDropPaise != null ? `${paise(v.thisMonth.costPerDropPaise)} / drop` : `${v.thisMonth?.drops || 0} drops`} /><Stat label="Rider" value={v.rider?.name || '—'} sub={v.rider?.phone} /><Stat label="Service due" value={v.serviceDue?.kmLeft != null ? `${v.serviceDue.kmLeft} km` : v.serviceDue?.on ? fmtDate(v.serviceDue.on) : '—'} warn={v.serviceDue?.kmLeft != null && v.serviceDue.kmLeft < 300} /></div>
    <div><b>Documents</b> {DOCS.map(([k, l]) => <span key={k} className={'badge mr-1 ' + (!v[k] ? 'bg-gray-100' : new Date(v[k]) < new Date() ? 'bg-red-100 text-red-800' : 'bg-leaf-100')}>{l} {v[k] ? fmtDate(v[k]) : '—'}</span>)}</div>
    <div><b>Expenses</b><table className="tbl text-xs mt-1"><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Odo</th><th>Details</th><th>By</th>{me?.role === 'ADMIN' && <th></th>}</tr></thead><tbody>{v.logs.map((l: any) => <tr key={l.id}><td>{fmtDate(l.date)}</td><td>{l.type}</td><td>{paise(l.amountPaise)}{l.litres ? ` · ${l.litres} l` : ''}</td><td>{l.odometerKm || '—'}</td><td>{[l.vendorName, l.description].filter(Boolean).join(' · ')}{l.nextDueKm ? ` · next ${l.nextDueKm} km` : ''}</td><td>{l.by || '—'}</td>{me?.role === 'ADMIN' && <td><button className="underline text-red-700" onClick={async () => { await api(`/admin/fleet/logs/${l.id}`, { method: 'DELETE' }); mutate(); }}>del</button></td>}</tr>)}</tbody></table>{!v.logs.length && <div className="text-gray-400">No expenses logged</div>}</div>
    <div><b>Pre-trip checks</b><table className="tbl text-xs mt-1"><thead><tr><th>When</th><th>Rider</th><th>Odo</th><th>Result</th></tr></thead><tbody>{v.checks.map((c: any) => <tr key={c.id}><td>{fmtDT(c.date)}</td><td>{c.rider}</td><td>{c.odometerStart ?? '—'}{c.odometerEnd ? ` → ${c.odometerEnd}` : ''}</td><td>{c.ok ? <span className="text-leaf-700">ok</span> : <span className="text-red-700">{Object.entries(c.checklist).filter(([, ok]) => !ok).map(([k]) => k).join(', ')}{c.issues ? ` — ${c.issues}` : ''}</span>}</td></tr>)}</tbody></table>{!v.checks.length && <div className="text-gray-400">No checks yet</div>}</div></div>}</Modal>;
}

function Vendors() {
  const me = getUser(); const { show, Toast } = useToast(); const { data, mutate } = useSWR('/admin/fleet/vendors', fetcher); const [edit, setEdit] = useState<any>(null); const [ledger, setLedger] = useState<string | null>(null); const [entry, setEntry] = useState<any>(null);
  const { data: led, mutate: mutL } = useSWR(ledger ? `/admin/fleet/vendors/${ledger}/ledger` : null, fetcher);
  const save = async () => { try { const { id, ...b } = edit; await api(id ? `/admin/fleet/vendors/${id}` : '/admin/fleet/vendors', { method: id ? 'PATCH' : 'POST', body: b }); setEdit(null); mutate(); } catch (e: any) { show(e.message, true); } };
  const post = async () => { try { await api(`/admin/fleet/vendors/${ledger}/ledger`, { body: { ...entry, amountPaise: Math.round(Number(entry.amount || 0) * 100) } }); setEntry(null); mutL(); mutate(); } catch (e: any) { show(e.message, true); } };
  const bill = async (id: string) => { const month = prompt('Bill hire for month (YYYY-MM)', thisMonth()); if (!month) return; try { const r = await api(`/admin/fleet/vendors/${id}/bill-hire`, { body: { month } }); show(r.results.map((x: any) => `${x.regNo}: ${x.skipped || paise(x.billedPaise)}`).join(' · ') || 'No hired vehicles'); mutate(); mutL(); } catch (e: any) { show(e.message, true); } };
  return <div><Toast /><div className="flex justify-end mb-3"><button className="btn-primary" onClick={() => setEdit({ name: '', contactName: '', phone: '', gstin: '', address: '', paymentTerms: '', bankNote: '', active: true })}>+ Vendor</button></div>
    <div className="card overflow-auto"><table className="tbl"><thead><tr><th>Vendor</th><th>Contact</th><th>Vehicles</th><th>Terms</th><th>Balance owed</th><th></th></tr></thead><tbody>
      {data?.map((v: any) => <tr key={v.id} className={v.active ? '' : 'opacity-50'}><td><b>{v.name}</b>{v.gstin && <><br /><small>{v.gstin}</small></>}</td><td className="text-xs">{v.contactName}<br />{v.phone}</td><td className="text-xs">{v.vehicles.map((x: any) => x.regNo).join(', ') || '—'}</td><td className="text-xs">{v.paymentTerms || '—'}</td><td className={v.balancePaise > 0 ? 'font-semibold' : ''}>{paise(v.balancePaise)}{v.overduePaise > 0 && <div className="text-xs text-red-700">{paise(v.overduePaise)} overdue</div>}</td>
        <td className="whitespace-nowrap"><button className="btn-secondary !py-0.5 !px-2 text-xs mr-1" onClick={() => setLedger(v.id)}>Ledger</button><button className="btn-secondary !py-0.5 !px-2 text-xs mr-1" onClick={() => bill(v.id)}>Bill hire</button><button className="btn-secondary !py-0.5 !px-2 text-xs" onClick={() => setEdit({ id: v.id, name: v.name, contactName: v.contactName || '', phone: v.phone, gstin: v.gstin || '', address: v.address || '', paymentTerms: v.paymentTerms || '', bankNote: v.bankNote || '', active: v.active })}>Edit</button></td></tr>)}</tbody></table>{data && !data.length && <Empty text="No vehicle vendors yet" />}</div>
    <Modal title={edit?.id ? 'Edit vendor' : 'New vehicle vendor'} open={!!edit} onClose={() => setEdit(null)}>{edit && <div className="grid grid-cols-2 gap-2">{[['name', 'Name'], ['contactName', 'Contact person'], ['phone', 'Phone (WhatsApp)'], ['gstin', 'GSTIN'], ['address', 'Address'], ['paymentTerms', 'Payment terms'], ['bankNote', 'Bank / UPI for payouts']].map(([k, l]) => <Field key={k} label={l}><input className="input" value={edit[k]} onChange={(e) => setEdit({ ...edit, [k]: e.target.value })} /></Field>)}<label className="text-sm flex items-center gap-2"><input type="checkbox" checked={edit.active} onChange={(e) => setEdit({ ...edit, active: e.target.checked })} /> active</label><div className="col-span-2 flex justify-end gap-2"><button className="btn-secondary" onClick={() => setEdit(null)}>Cancel</button><button className="btn-primary" onClick={save}>Save</button></div></div>}</Modal>
    <Modal title={led ? `${led.vendor.name} · ledger` : 'Ledger'} open={!!ledger} onClose={() => setLedger(null)}>{led && <div className="text-sm"><div className="flex gap-4 mb-2 flex-wrap"><span>Billed <b>{paise(led.billed)}</b></span><span>Paid <b>{paise(led.paid)}</b></span><span>Balance <b className={led.balancePaise > 0 ? 'text-red-700' : 'text-leaf-700'}>{paise(led.balancePaise)}</b></span><span className="ml-auto flex gap-1"><button className="btn-secondary !py-0.5 !px-2 text-xs" onClick={() => setEntry({ reason: 'BILL', amount: '', ref: '', note: '', dueDate: '', method: '' })}>+ Bill</button>{me?.role === 'ADMIN' && <button className="btn-primary !py-0.5 !px-2 text-xs" onClick={() => setEntry({ reason: 'PAYMENT', amount: Math.max(0, led.balancePaise) / 100, ref: '', note: '', method: 'UPI', dueDate: '' })}>+ Payment</button>}</span></div>
      {entry && <div className="card grid grid-cols-2 md:grid-cols-5 gap-2 mb-2"><Field label="Type"><select className="input" value={entry.reason} onChange={(e) => setEntry({ ...entry, reason: e.target.value })}><option>BILL</option>{me?.role === 'ADMIN' && <option>PAYMENT</option>}<option>ADJUST</option></select></Field><Field label="Amount ₹"><input type="number" className="input" value={entry.amount} onChange={(e) => setEntry({ ...entry, amount: e.target.value })} /></Field>{entry.reason === 'PAYMENT' ? <><Field label="Method"><select className="input" value={entry.method} onChange={(e) => setEntry({ ...entry, method: e.target.value })}>{['UPI', 'BANK', 'CASH'].map((m) => <option key={m}>{m}</option>)}</select></Field><Field label="UTR / ref"><input className="input" value={entry.ref} onChange={(e) => setEntry({ ...entry, ref: e.target.value })} /></Field></> : <><Field label="Due date"><input type="date" className="input" value={entry.dueDate} onChange={(e) => setEntry({ ...entry, dueDate: e.target.value })} /></Field><Field label="Invoice no"><input className="input" value={entry.ref} onChange={(e) => setEntry({ ...entry, ref: e.target.value })} /></Field></>}<Field label="Note"><input className="input" value={entry.note} onChange={(e) => setEntry({ ...entry, note: e.target.value })} /></Field><div className="col-span-full flex justify-end gap-2"><button className="btn-secondary !py-1" onClick={() => setEntry(null)}>Cancel</button><button className="btn-primary !py-1" onClick={post}>Post</button></div></div>}
      <table className="tbl text-xs"><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Running</th><th>Details</th></tr></thead><tbody>{led.rows.map((r: any) => <tr key={r.id}><td>{fmtDate(r.date)}</td><td><StatusBadge s={r.reason} /></td><td className={r.deltaPaise < 0 ? 'text-leaf-700' : ''}>{r.deltaPaise < 0 ? '−' : ''}{paise(Math.abs(r.deltaPaise))}</td><td>{paise(r.runningPaise)}</td><td>{[r.note, r.ref && `ref ${r.ref}`, r.method, r.dueDate && `due ${fmtDate(r.dueDate)}`].filter(Boolean).join(' · ')}</td></tr>)}</tbody></table>{!led.rows.length && <Empty text="No entries" />}</div>}</Modal></div>;
}

function Expenses() {
  const [month, setMonth] = useState(thisMonth()); const [type, setType] = useState(''); const { data } = useSWR(`/admin/fleet/logs?month=${month}${type ? '&type=' + type : ''}`, fetcher);
  const total = data?.reduce((a: number, l: any) => a + l.amountPaise, 0) || 0;
  return <div><div className="flex gap-2 items-center mb-3 flex-wrap"><input type="month" className="input" value={month} onChange={(e) => setMonth(e.target.value)} /><select className="input" value={type} onChange={(e) => setType(e.target.value)}><option value="">All types</option>{LOGT.map((t) => <option key={t}>{t}</option>)}</select>{['csv', 'xlsx', 'pdf'].map((f) => <a key={f} className="btn-secondary !py-1" target="_blank" href={`${API}/v1/admin/fleet/export?dataset=logs&month=${month}&format=${f}&t=${getToken()}`}>{f.toUpperCase()}</a>)}<span className="ml-auto text-sm">Total <b>{paise(total)}</b></span></div>
    <div className="card overflow-auto"><table className="tbl text-sm"><thead><tr><th>Date</th><th>Vehicle</th><th>Type</th><th>Amount</th><th>Litres</th><th>Odometer</th><th>Vendor</th><th>Description</th></tr></thead><tbody>{data?.map((l: any) => <tr key={l.id}><td className="text-xs">{fmtDate(l.date)}</td><td>{l.vehicle.regNo}</td><td><StatusBadge s={l.type} /></td><td>{paise(l.amountPaise)}</td><td>{l.litres ?? '—'}</td><td>{l.odometerKm ?? '—'}</td><td className="text-xs">{l.vendorName || '—'}</td><td className="text-xs">{l.description || '—'}</td></tr>)}</tbody></table>{data && !data.length && <Empty text="No expenses this month" />}</div></div>;
}

function Checks() {
  const { data } = useSWR('/admin/fleet/vehicles', fetcher);
  return <div className="card overflow-auto"><table className="tbl text-sm"><thead><tr><th>Vehicle</th><th>Rider</th><th>Last pre-trip check</th><th>Result</th><th>Status</th></tr></thead><tbody>{data?.filter((v: any) => v.active).map((v: any) => <tr key={v.id}><td><b>{v.regNo}</b></td><td className="text-xs">{v.rider?.name || '—'}</td><td className="text-xs">{v.lastCheck ? fmtDT(v.lastCheck.date) : <span className="text-amber-700">never</span>}</td><td className="text-xs">{v.lastCheck ? (v.lastCheck.ok ? <span className="text-leaf-700">ok · {v.lastCheck.odometerStart ?? '—'}{v.lastCheck.odometerEnd ? ` → ${v.lastCheck.odometerEnd} km` : ''}</span> : <span className="text-red-700">{Object.entries(v.lastCheck.checklist).filter(([, ok]) => !ok).map(([k]) => k).join(', ')}{v.lastCheck.issues ? ` — ${v.lastCheck.issues}` : ''}</span>) : '—'}</td><td><StatusBadge s={v.status} /></td></tr>)}</tbody></table><p className="text-xs text-gray-500 mt-2">Riders do the checklist in the app before starting a route. Failed brakes / tyres / lights put the vehicle in MAINTENANCE and block route assignment until Ops logs the repair.</p></div>;
}
